"""Original writing and speaking source items for the initial practice form."""

REPEATS = ['Welcome to the learning center.',
 'The help desk is beside the main entrance.',
 'You can reserve a study room through the student portal.',
 'Please return borrowed equipment before the center closes on Friday evening.',
 'Students who need help with their assignments can book an appointment with a tutor.',
 "Although the computer rooms are open late, technical support is only available until six o'clock.",
 'Please complete the short orientation before you reserve our recording studio for the first time.',
 'Students should label each file before uploading it to the shared folder.',
 'The afternoon workshop explains how local residents use public gardens.',
 'Because the road is closed, the shuttle will stop near the east gate.',
 'The scholarship committee considers academic progress and community work.',
 'After the lecture, write one question that connects the evidence to the theory.']

INTERVIEWS = [('S08',
  'We are studying how students learn. Where do you usually study, and what makes that place useful for you?',
  ['study', 'place', 'because'],
  'Describe a familiar place and explain how it supports your study routine.'),
 ('S09',
  'Think about a time when you had to learn something difficult. What did you do, and how did it help?',
  ['learn', 'practice', 'help'],
  'Give a specific experience, describe your action, and explain the result.'),
 ('S10',
  'Some students study alone, while others work with classmates. Which approach do you prefer for a challenging '
  'course, and why?',
  ['study', 'classmates', 'prefer'],
  'Choose an approach and explain its value for a demanding course with an example.'),
 ('S11',
  'Universities are considering replacing some quiet study rooms with collaborative spaces. What effect might this '
  'have on students, and what would you recommend?',
  ['students', 'spaces', 'quiet'],
  'Consider different study needs, predict an effect, and justify a recommendation.'),
 ('S17',
  'Describe a time you changed your plan after receiving useful advice. What did you learn?',
  ['advice', 'changed', 'learned'],
  'Tell a brief sequence of events and identify the lesson.'),
 ('S18',
  'Which is more important for a group project: assigning roles early or allowing roles to develop naturally? Why?',
  ['group', 'roles', 'project'],
  'Choose one approach and explain how it affects collaboration.'),
 ('S19',
  'What is one way a university could help new students make friends? Explain how your idea would work.',
  ['students', 'university', 'friends'],
  'Propose one practical program and describe its effect.'),
 ('S20',
  'Do you learn more from correcting your own mistakes or from watching an expert? Support your answer.',
  ['mistakes', 'expert', 'learn'],
  'Compare the two sources of learning and give a reasoned choice.'),
 ('S21',
  'Describe a piece of technology that has changed how you study. What did you do before using it?',
  ['technology', 'study', 'before'],
  'Identify the technology and contrast your earlier and current routine.'),
 ('S22',
  'Should students be allowed to choose some classes outside their major? Explain one advantage.',
  ['students', 'classes', 'major'],
  'State your position and explain a concrete academic advantage.'),
 ('S23',
  'Tell the interviewer about an event that helped you understand a different perspective.',
  ['event', 'perspective', 'understand'],
  'Describe the event and explain how your perspective changed.'),
 ('S24',
  'Would you prefer to study in the morning or late at night? Give two reasons.',
  ['morning', 'night', 'reasons'],
  'Make a direct choice and provide two connected reasons.'),
 ('S25',
  'What advice would you give to a student preparing for a demanding exam in one month?',
  ['advice', 'exam', 'month'],
  'Offer a practical plan with at least two steps.')]

SENTENCE_ITEMS = [('W01',
  ['the', 'research', 'team', 'published', 'its', 'results', 'online'],
  'Arrange the words to make a complete sentence.',
  'The research team published its results online.'),
 ('W02',
  ['students', 'can', 'reserve', 'a', 'study', 'room', 'through', 'the', 'library'],
  'Arrange the words to make a complete sentence.',
  'Students can reserve a study room through the library.'),
 ('W03',
  ['because', 'the', 'trail', 'was', 'wet', 'the', 'class', 'walked', 'slowly'],
  'Arrange the words to make a complete sentence.',
  'Because the trail was wet, the class walked slowly.'),
 ('W04',
  ['our', 'professor', 'asked', 'whether', 'the', 'evidence', 'supported', 'the', 'claim'],
  'Arrange the words to make a complete sentence.',
  'Our professor asked whether the evidence supported the claim.'),
 ('W05',
  ['the', 'new', 'schedule', 'allows', 'commuters', 'to', 'avoid', 'rush', 'hour'],
  'Arrange the words to make a complete sentence.',
  'The new schedule allows commuters to avoid rush hour.'),
 ('W06',
  ['after', 'the', 'experiment', 'we', 'recorded', 'each', 'measurement', 'carefully'],
  'Arrange the words to make a complete sentence.',
  'After the experiment, we recorded each measurement carefully.'),
 ('W07',
  ['the', 'museum', 'will', 'display', 'photographs', 'from', 'the', 'early', 'expedition'],
  'Arrange the words to make a complete sentence.',
  'The museum will display photographs from the early expedition.'),
 ('W08',
  ['if', 'the', 'weather', 'improves', 'the', 'market', 'will', 'open', 'outside'],
  'Arrange the words to make a complete sentence.',
  'If the weather improves, the market will open outside.'),
 ('W09',
  ['many', 'languages', 'borrow', 'words', 'when', 'cultures', 'come', 'into', 'contact'],
  'Arrange the words to make a complete sentence.',
  'Many languages borrow words when cultures come into contact.'),
 ('W10',
  ['the', 'advisor', 'recommended', 'that', 'I', 'compare', 'several', 'sources'],
  'Arrange the words to make a complete sentence.',
  'The advisor recommended that I compare several sources.')]

EMAILS = [('W11',
  'You arranged to discuss your statistics project with your professor. The appointment has been moved to a time when you have a required class. You still need advice before continuing your analysis and would like to find another arrangement.\n\nWrite an email to Professor Lee. In your email:\n- Explain why you cannot attend the new appointment.\n- Describe the part of your statistics project you need help with.\n- Request another appointment and suggest how you can prepare for it.\n\nWrite in complete sentences.\nTo: Professor Lee\nSubject: Request to reschedule our appointment',
  ['professor', 'appointment', 'statistics'],
  'Write a polite request, explain the conflict, and identify the topic you need to discuss.'),
 ('W12',
  'You live in a university residence hall where two laundry machines are not working properly. Other residents are also having difficulty doing their laundry, and you do not know when the machines will be repaired. You want the housing staff to investigate.\n\nWrite an email to the housing office. In your email:\n- Describe the problem and its effect on residents.\n- Ask about inspecting or repairing the machines.\n- Suggest a temporary arrangement while repairs are being made.\n\nWrite in complete sentences.\nTo: the housing office\nSubject: Laundry room repairs',
  ['laundry', 'machines', 'housing'],
  'Describe the practical problem and offer a reasonable temporary solution.'),
 ('W13',
  'You borrowed a camera from the university media desk for a class project. You have not been able to finish the photographs and need the camera for two more days. You understand that other students may already have reserved the equipment.\n\nWrite an email to the media desk team. In your email:\n- Identify your loan and request a two-day extension.\n- Explain why the extra time is necessary for your project.\n- Ask about an alternative if extending the loan is not possible.\n\nWrite in complete sentences.\nTo: the media desk team\nSubject: Request for a camera loan extension',
  ['camera', 'extension', 'project'],
  'State the request, give a brief reason, and acknowledge the return policy.'),
 ('W14',
  'A visiting researcher will give a talk about urban gardens at your university. You think a classmate would be interested because the topic connects with the classmate’s current project. You would like to attend together rather than simply forward an event advertisement.\n\nWrite an email to your classmate Jamie. In your email:\n- Invite your classmate and provide useful event information.\n- Explain how the talk could help your classmate’s project.\n- Suggest an arrangement for attending together.\n\nWrite in complete sentences.\nTo: your classmate Jamie\nSubject: Invitation to the urban gardens talk',
  ['researcher', 'gardens', 'useful'],
  'Invite the classmate and connect the event to a specific academic interest.'),
 ('W15',
  'You have signed up for a field trip, but the directions you received do not clearly explain where the group will meet. You are also unsure which equipment or supplies participants need. You want to prepare without delaying the group on the day.\n\nWrite an email to the field trip organizer. In your email:\n- Explain what is unclear in the directions.\n- Ask for confirmation of the meeting place and arrival time.\n- Ask what participants should bring and what will be provided.\n\nWrite in complete sentences.\nTo: the field trip organizer\nSubject: Questions about field trip arrangements',
  ['meeting', 'directions', 'bring'],
  'Ask both practical questions in a clear, courteous email.'),
 ('W16',
  'Attendance at your student club’s meetings has been lower than expected. Members are interested in the club, but the current meeting format may make it difficult for them to stay involved. The club leader has invited practical suggestions rather than requests for a larger budget.\n\nWrite an email to the club leader. In your email:\n- Describe one concern about the current meeting format.\n- Propose a specific change and explain how it could help attendance.\n- Suggest a practical way to try the change.\n\nWrite in complete sentences.\nTo: the club leader\nSubject: A suggestion for our meetings',
  ['club', 'attendance', 'format'],
  'Propose one change and explain how it could improve attendance.'),
 ('W17',
  'You were helping someone find an accessible entrance to a campus building when you noticed that the entrance was missing from the campus map. People unfamiliar with the building may follow a route they cannot use. You want campus services to make the information clearer.\n\nWrite an email to campus services. In your email:\n- Identify the missing information and explain why it matters.\n- Describe the map update you recommend.\n- Suggest how the update could be made useful to visitors.\n\nWrite in complete sentences.\nTo: campus services\nSubject: Accessible entrance missing from the map',
  ['map', 'accessible', 'update'],
  'Identify the missing information and explain why the update matters.'),
 ('W26',
  'You reserved a library study room to prepare a presentation with your group. When you checked the equipment, the projector did not work. Your group needs to review visual material together, and the reservation is still important to your preparation schedule.\n\nWrite an email to the library desk. In your email:\n- Explain the equipment problem and the purpose of your booking.\n- Describe what your group needs for the session.\n- Request a replacement room or a suitable working device.\n\nWrite in complete sentences.\nTo: the library desk\nSubject: Projector problem in a reserved room',
  ['study', 'projector', 'replacement'],
  'Describe the equipment problem and make a clear request for a practical solution.'),
 ('W27',
  'You have agreed to work a volunteer shift, but a required laboratory class now conflicts with it. You want to inform the coordinator early enough for the schedule to be adjusted. You are still willing to complete your volunteer commitment at another time.\n\nWrite an email to the volunteer coordinator. In your email:\n- Explain the conflict and identify the shift affected.\n- Request a switch and offer an alternative time.\n- Explain how you can help minimize disruption to the schedule.\n\nWrite in complete sentences.\nTo: the volunteer coordinator\nSubject: Request to change a volunteer shift',
  ['volunteer', 'shift', 'lab'],
  'Explain the conflict, request a switch, and suggest a specific alternative.'),
 ('W28',
  'After a class discussion, your professor sent you an article related to an idea you had asked about. Reading it has helped you think more clearly about your own work. You want to acknowledge the help in a specific, useful message.\n\nWrite an email to your professor. In your email:\n- Thank the professor for sharing the article.\n- Explain one idea you found useful.\n- Describe how you plan to apply that idea in your work.\n\nWrite in complete sentences.\nTo: your professor\nSubject: Thank you for the article',
  ['article', 'professor', 'use'],
  'Thank the professor and connect the article to a concrete academic task.')]

DISCUSSIONS = [('W18',
  'Professor: A university is reviewing its graduation requirements. Students already complete a substantial set of courses in their own departments, but the university also wants graduates to understand ways of thinking beyond a single field. Should universities require students to take one course in a subject outside their major?\nStudent A: It helps students discover connections between fields. Someone studying engineering might learn to consider social consequences in a history course. Students may never discover those connections if they choose only subjects they already feel comfortable studying.\nStudent B: It takes time away from required courses. In a program with tightly sequenced laboratory courses, even one extra requirement can make scheduling difficult. I would rather let students use their limited elective space for skills directly related to their plans.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['major', 'course', 'because'],
  'Take a clear position, address one concern, and support the position with a specific reason.'),
 ('W19',
  'Professor: A growing city has enough money for one major improvement this year. Residents have requested both better shared outdoor space and easier travel between neighborhoods, so the council needs to decide which benefit should take priority. Is it better for a city to invest in public parks or in improved public transportation?\nStudent A: Parks improve health and community life. A well-designed park gives people somewhere to exercise and meet without paying for an activity. That is especially important in neighborhoods where many homes have little outdoor space.\nStudent B: Transportation helps people reach jobs. People cannot benefit equally from city facilities if reaching them is difficult. More reliable transportation would make everyday opportunities accessible to residents who cannot afford a car, not just improve occasional trips.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['parks', 'transportation', 'community'],
  'Choose one investment and compare its effect with the other option.'),
 ('W20',
  'Professor: In some university seminars, discussion is central to learning, but not all students speak equally often. Instructors are considering whether participation should affect course grades and what behavior such a policy would encourage. Should students receive grades for participating in class discussions?\nStudent A: Grades encourage preparation. When discussion counts, students have a reason to read carefully beforehand instead of relying on others. Preparing to explain a point can also reveal misunderstandings that remain hidden during silent reading.\nStudent B: Quiet students may have valuable ideas too. Speaking frequently is not the same as thinking carefully. A student may need time to organize an answer, especially in another language, and should not be treated as unprepared simply for speaking less.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['grades', 'discussion', 'students'],
  'State your view and explain how participation grades could be fair or unfair.'),
 ('W21',
  'Professor: A university can expand either its online course offerings or its small classroom seminars next year. Both options could improve learning, but they use staff time and resources differently and may serve different groups of students. Should universities provide more online courses or more small in-person seminars?\nStudent A: Online courses are flexible. Students who commute or have jobs can fit learning around responsibilities they cannot easily change. Requiring everyone to be in the same room at the same time can exclude capable students from useful courses.\nStudent B: Seminars create deeper conversations. A small group can question an interpretation and hear an immediate reply. That exchange often changes the direction of a conversation in ways a student working independently would not anticipate.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['online', 'seminars', 'flexible'],
  'Support one format while acknowledging a strength of the other.'),
 ('W22',
  'Professor: A university is considering concentrating its usual teaching hours into four days rather than five. The total amount of instruction would stay the same, so some daily schedules would become longer in exchange for a free weekday. Is a four-day class week better than classes spread across five days?\nStudent A: A four-day week leaves time for work. An uninterrupted weekday is easier to use for a work shift or an appointment than several short gaps between classes. Commuters could also avoid an additional round trip without losing teaching time.\nStudent B: Five days creates a steadier routine. Spreading classes out gives students time to review one lesson before the next. Very long teaching days can leave people tired, so fewer trips to campus might come at the expense of attention.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['week', 'routine', 'work'],
  'Give a position with a practical example about time or routine.'),
 ('W23',
  'Professor: A campus dining service wants to help students understand the consequences of their food choices. One proposal is to add environmental information beside menu items, although estimates may depend on what aspects of production are measured. Should campus dining halls label the environmental impact of meals?\nStudent A: Labels help students make informed choices. Students already compare prices and ingredients when deciding what to eat. Clear environmental information would let people include another concern in that decision instead of having to research every meal themselves.\nStudent B: Labels may oversimplify complex information. A single symbol can make uncertain estimates look exact. Students might assume a low rating settles every environmental question, even when transport, water use, and packaging point in different directions.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['labels', 'meals', 'information'],
  'Explain whether labels would improve decisions and mention a limitation.'),
 ('W24',
  'Professor: Some universities encourage new students to live in university housing during their first year. Others leave the decision entirely to students and families. Housing choices may affect both adjustment to university life and the cost of attending. Should first-year students live on campus?\nStudent A: Campus housing helps students build a support network. It is easier to ask a classmate for help or join an activity when other students are nearby. Those everyday encounters can matter for someone arriving without friends or knowledge of the campus.\nStudent B: Living at home can reduce costs. A student with a supportive home nearby may already have a good place to study. Paying for another room could create financial pressure without adding benefits large enough to justify the expense.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['campus', 'students', 'costs'],
  'Weigh community benefits against cost and give a justified recommendation.'),
 ('W25',
  'Professor: A museum is reviewing how it serves young people in its own community. It could remove admission charges for local students, but it would still need to pay for staff, conservation, and exhibitions that those visitors would use. Should museums offer free admission to local students?\nStudent A: Free access encourages learning. Students could return to examine an object instead of trying to see everything in one paid visit. More frequent contact would make the museum part of everyday learning rather than a rare outing.\nStudent B: Museums need admission revenue. Free entry does not make an exhibition free to operate. If lost ticket income leads to fewer programs or shorter opening hours, students might gain admission but lose some of the experiences that make visiting worthwhile.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['museums', 'students', 'access'],
  'State a policy recommendation and explain how the museum could manage the trade-off.'),
 ('W29',
  'Professor: A department is deciding which course materials to provide digitally and which to keep in print. Students use textbooks for different purposes, from checking a fact quickly to reading and annotating a difficult chapter in depth. Should universities replace some printed textbooks with digital versions?\nStudent A: Digital texts are easier to update. When examples or data change, a digital edition can be corrected without replacing a whole stock of books. Search tools can also help students locate related material across a long text.\nStudent B: Printed books are easier to annotate. For sustained reading, I prefer seeing the page layout and writing comments in the margins. Switching between windows can make it harder to follow an argument, even if finding individual words is faster.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['digital', 'textbooks', 'annotate'],
  'Choose a format and explain how students could manage its main limitation.'),
 ('W30',
  'Professor: During examinations, students often ask for additional places to study in the evening. Keeping campus buildings open later could help, but the university must decide whether the extra use would justify the support and operating costs. Should campus buildings stay open later during exam periods?\nStudent A: Longer hours give students quiet places to study. Some students share crowded homes or have responsibilities that limit daytime study. An evening study room can offer a reliable quiet place when their usual surroundings do not support concentration.\nStudent B: Staffing and energy costs increase. Opening an entire building for a few people still requires staff and lighting. Resources spent on late access might otherwise improve the services that large numbers of students use during ordinary hours.\n\nWrite a post expressing and supporting your own view. Contribute an idea to the discussion rather than simply repeating another student.',
  ['buildings', 'students', 'costs'],
  'Recommend a policy and address both study access and operating costs.')]
