"""Additional original reading materials, not reproduced from ETS or screenshots."""

CLOZE_ALTERNATIVES = {'R125': ['recognise', 'gnise']}

CLOZE_PASSAGES = [
    ("Fossils and evidence", 'A fossil is a trace of an organism that lived in the past. Some {{fossils}} form {{when}} sediment {{covers}} a {{plant}} or {{animal}} before {{its}} remains {{decay}} completely, {{and}} minerals {{replace}} the {{original}} material. Soft tissues usually disappear, while harder parts may survive. This uneven preservation means the fossil record cannot offer a complete picture of every ancient community. Researchers therefore compare fossils with other evidence, including the rocks around them. A shell found far from the modern coast may suggest that water once covered the area, but its position and age must also be investigated.'),
    ("The night sky", 'City lights can make familiar stars difficult to see. Light {{scatters}} from {{atmospheric}} particles {{and}} creates {{bright}} backgrounds {{that}} reduce {{the}} contrast {{between}} distant {{stars}} and {{their}} immediate {{surroundings}}. Astronomers prefer dark locations for observing faint objects, although darkness alone does not guarantee a useful site. Clouds, moisture, and unstable air can also interfere with observations. Some communities now direct street lighting downward and dim it when traffic is low. Such changes preserve useful illumination on the ground while reducing unnecessary light above it.'),
    ("Seeds on the move", 'Plants cannot walk away from the places where they grow. Their {{seeds}} can {{travel}} with {{wind}} or {{water}}, while {{others}} attach {{themselves}} to {{animals}} that {{carry}} them {{far}} from {{home}}. Distance may reduce competition between a parent plant and its offspring, but a journey is useful only if the seed reaches a suitable place. Large seeds often contain more stored food, whereas small ones may be carried farther. No single strategy succeeds in every environment. Biologists study these differences by tracking where seeds land and which seedlings survive, rather than simply counting how many seeds a plant produces.'),
    ("Reading old maps", 'Historical maps reveal more than the location of roads and rivers. Maps {{also}} reveal {{which}} places {{their}} makers {{considered}} important {{and}} how {{available}} information {{shaped}} the {{symbols}} chosen {{for}} different {{audiences}}. A large symbol may mark a politically significant town rather than a physically large settlement. An empty region might reflect limited knowledge instead of an absence of people. Historians compare maps with letters, travel accounts, and later surveys to understand such choices. They also examine the intended audience.'),
    ("Sound underwater", 'Sound can change direction as it travels through layers of ocean water. Temperature {{gradients}} change {{how}} quickly {{sound}} travels {{through}} water, {{and}} rising {{pressure}} at {{greater}} depths {{also}} affects {{its}} local {{speed}}. A temperature gradient is a change in temperature from one place to another. When sound speed differs between layers, waves can bend toward slower regions. Changes in temperature and pressure can therefore guide some sounds over long distances. Scientists record whale calls with underwater microphones, but a strong signal does not necessarily mean the animal is nearby.'),
    ("Ceramics and temperature", 'Clay vessels have been made in many societies for thousands of years. Heating {{changes}} the {{structure}} of {{clay}} and {{makes}} finished {{vessels}} stronger {{than}} the {{material}} from {{which}} craftspeople {{originally}} shaped {{them}}. The firing temperature influences how much water the vessel can absorb and whether certain decorations survive. Archaeologists examine fragments because their properties can reveal manufacturing choices even when the original object is broken. Similar-looking pots may have been produced with different techniques. Experiments using local clay help test these possibilities, although a successful modern reconstruction does not prove that ancient craftspeople followed exactly the same procedure.'),
    ("Pollination networks", 'Flowering plants often depend on animals to move pollen between flowers. Different {{species}} visit {{flowers}} at {{different}} times, {{which}} can {{help}} maintain {{pollination}} when {{conditions}} change {{during}} the {{warmer}} growing {{season}}. A network with several pollinators may continue functioning when one species becomes less common. However, not every visitor transfers pollen effectively, and some plants depend on a narrow range of partners. Researchers therefore record both the number of visits and their results. Protecting nesting sites as well as flowers can support the whole system.'),
    ("Learning a route", 'People often remember a new route by noticing distinctive places along it. These {{landmarks}} help {{travelers}} on {{unfamiliar}} streets {{because}} people {{recognize}} their {{shapes}} and {{use}} them {{to}} decide {{where}} to {{turn}}. Repeated journeys can gradually produce a more general understanding of the area. This mental representation allows a person to find an alternative path when a familiar road is closed. Navigation tools can support learning, but constantly following instructions may draw attention away from surrounding features. Studies compare later route knowledge to determine whether a tool helped users understand the environment or merely reach a destination.'),
    ("Desert surfaces", 'Desert soil may be covered by a thin layer of living organisms. These {{organisms}} bind {{loose}} particles {{together}}, so {{the}} soil {{becomes}} less {{likely}} to {{blow}} away {{when}} strong {{winds}} cross {{it}}. The layer develops slowly, so damage caused by a vehicle can remain visible long after the vehicle has left. Researchers studying restoration must consider both the organisms and the conditions they require. Simply moving material from a healthy site may fail if temperature or moisture differs. Protecting undisturbed areas is therefore an important part of learning how these communities recover.'),
    ("Messages and context", 'The meaning of a short message is not always contained in its words alone. Readers {{infer}} unstated {{intentions}} from {{contextual}} clues, {{while}} shared {{assumptions}} constrain {{interpretations}} that {{might}} otherwise {{seem}} equally {{plausible}} without {{explanation}}. A note saying that a room is cold might be a description, a complaint, or a request to close a window. The surrounding situation helps distinguish these possibilities. Linguists study such examples to understand how people communicate efficiently without explaining every assumption. Misunderstandings become more likely when participants have different expectations.'),
    ("Coastal dunes", 'Sand dunes along a coast are shaped by both wind and vegetation. Coastal {{plants}} slow {{the}} wind {{near}} ground {{level}} and {{allow}} sand {{to}} collect {{around}} their {{stems}} over {{several}} successive {{seasons}}. As a dune grows, it can provide some protection from waves during storms. Its shape is not permanent, however, and movement is part of the coastal system. Managers may install walkways to reduce damage to plants while still allowing people to reach the beach. Whether a restoration project succeeds depends on local conditions.'),
    ("Museum labels", 'An exhibition label helps visitors connect an object with a larger story. Visitors {{often}} have {{limited}} time {{when}} they {{move}} through {{busy}} rooms. {{Each}} label {{therefore}} needs {{to}} explain {{its}} object {{clearly}}. A useful label identifies the object and explains why it matters without assuming extensive prior knowledge. The choice of words can also affect whose perspective is represented. Curators sometimes invite community members to review descriptions and suggest missing context. Shorter text is not automatically clearer: removing an unfamiliar term may help, but deleting the relationship between two ideas can leave a reader with less understanding than before.'),
]


def item(prompt, correct, a, b, c, explanation):
    """Keep authoring compact; the builder rotates the correct option position."""
    return (prompt, [correct, a, b, c], 0, explanation)


DAILY_PASSAGES = [
    ("Community research fair — agenda", "COMMUNITY RESEARCH FAIR\nSaturday · North Hall\n9:00 Welcome: How local questions become research projects\n10:00 Workshop: Working with neighborhood data\n12:00 Lunch with community partners\n13:30 Student project demonstrations\n15:00 Round table: Planning next year's partnerships\nAll sessions explore collaboration between residents and university researchers. Workshop places require advance registration; other sessions are open to everyone.", [
        item('What is the main aim of the fair?', 'To develop collaboration on local research.', 'To offer training exclusively for professional researchers.', 'To recruit residents to judge a student project competition.', 'To present completed studies without planning future work.', "读懂：collaboration 是“一起合作做事”。文末说所有活动都围绕居民与大学研究者的合作，最后的圆桌会还要规划明年的伙伴关系。\n解析：所以主旨是推动本地研究合作。并非只培训专业研究人员；学生展示不等于招募居民当比赛评委；规划明年也直接排除了“只展示成果、不谈未来”。\n下次：做活动主旨题，先看总说明，再用开场和结尾核对共同目标。不要把其中一个小环节当成整场活动的目的。"),
        item("Which activity requires an advance booking?", "The workshop at 10:00.", "The welcome session.", "Lunch with community partners.", "The afternoon round table.", "读懂：Workshop places require advance registration 意思是“工作坊名额需要提前登记”；紧接着说其他活动人人都能参加。日程中工作坊在十点。\n解析：要提前预约的是十点的工作坊。欢迎会、与社区伙伴共进午餐、下午圆桌会都属于其他活动，不能把工作坊的报名要求套到它们身上。\n下次：问哪项需要预约时，先找 require、registration 等要求词，再把对应的活动名与时间表配对，并检查是否明确排除了其他活动。"),
    ]),
    ("Student design showcase — flyer", "DESIGN FOR EVERYDAY LIFE\nStudent Showcase · Thursday, May 8 · 16:00–19:00\nEngineering Atrium\nExplore prototypes, meet student designers, and vote for the audience award. Admission is free. Presenters must send a project summary by April 20. Visitors should register by May 2 and include any accessibility requirements in the registration form. Printed programs will be available at the entrance.", [
        item('How should visitors request accessibility support?', 'Mention their requirements when registering.', 'Ask the presenters when submitting their project summaries.', 'Add their requirements to an audience award ballot.', 'Write their requirements in a printed program at the entrance.', "读懂：accessibility requirements 指无障碍支持需求，例如参加活动时需要的便利安排。文中要求访客报名时把这类需求填进 registration form，即报名表。\n解析：应在报名时说明需求。项目摘要是展示者要交的，不是访客求助的渠道；观众投票用于评奖；入口的纸质节目单也不是申请表。\n下次：遇到“如何申请支持”的通知题，按“谁提出—填写什么—通过哪里提交”定位流程，别把文中所有表格、材料都当成同一种用途。"),
        item("Who must meet the April 20 deadline?", "Students presenting a project.", "All visitors to the showcase.", "People voting for the award.", "People collecting programs.", "读懂：Presenters 是展示项目的人，必须在四月二十日前交项目摘要；Visitors 是来参观的人，报名截止日是五月二日。\n解析：四月二十日的要求只对应展示项目的学生。所有访客有另一个截止日；投票者和领取节目单的人也没有被要求在四月二十日前完成这些活动。\n下次：一篇通知有多个日期时，做“日期—对象—要办的事”三栏配对。题目问谁，就沿同一句里的主语找对象，不要只看到截止日期就认为适用于所有人。"),
    ]),
    ("Email about a book order", "To: Seminar participants\nSubject: Course reader\nThe printed course reader will arrive next Tuesday, one week later than expected. For Monday's seminar, use the first chapter posted on the course site. Please do not buy the older edition: its page numbers and case studies differ. If you have already paid the bookstore, your order remains valid. I will bring several loan copies for students who cannot access the online chapter.", [
        item("What should students read before Monday?", "The chapter on the course website.", 'The corresponding chapter in the older edition.', 'The entire reader posted on the course site.', 'The first chapter only after the printed reader arrives.', '读懂：“the first chapter posted on the course site”是课程网站上的第一章。周一上课，纸质读本周二才到，所以老师安排先读网上这一章。\n解析：应读网站上的章节。旧版的页码和案例不同，不能拿旧版对应章节替代；网站只提供了第一章，并非整本；等纸本到了再读，就赶不上周一的课。\n下次：材料延期时，先排出上课日与到货日，再找老师指定的临时材料；核对版本、阅读范围和完成时间三项。'),
        item("What can a student who already paid infer?", "There is no need to place a new order.", "The order has been canceled.", "The older edition will be substituted.", "A second payment is due on Monday.", "读懂：your order remains valid 意思是“你的订单仍然有效”。这句话专门对已经向书店付款的学生说，延迟的是书到货的时间。\n解析：既然原订单有效，就不必重新下单。它没有被取消；旧版也不会自动替代新版，老师反而提醒别买旧版；邮件更没有要求周一再付款。\n下次：做邮件推断题，先确定发生了哪项变化，再看哪些安排被明确保留。到货延迟不等于订单失效，不能凭一个变化自行添加取消、换货或二次收费。"),
    ]),
    ("Bicycle repair service", "CAMPUS CYCLE DESK\nDrop-in safety checks: Tuesday and Thursday, 11:00–14:00\nA safety check is free and includes brakes, lights, and tire pressure. Replacement parts are charged separately. Repairs taking more than twenty minutes require an appointment. Leave bicycles only with a staff member; the rack outside is not a drop-off point. The desk closes during heavy rain because the work area is outdoors.", [
        item("Which cost might a visitor have to pay?", "The price of a replacement part.", "A fee for checking tire pressure.", 'A separate charge for checking the brakes.', "A fee for every safety check.", '读懂：A safety check is free 是“安全检查免费”，包括刹车、车灯和胎压；Replacement parts are charged separately 是“更换用的零件另收费”。\n解析：可能要付的是替换零件的钱。查胎压已经包含在免费检查内；并非每次安全检查都收费；刹车检查也已包含在免费安全检查内。\n下次：看服务费用题时，分开列“免费包含什么”和“额外收费什么”。特别留意 separately，不能把零件费误读成检查费，别把免费检查的项目拆成新的收费项目。'),
        item('What should someone needing a lengthy repair do?', 'Arrange an appointment.', 'Join the free safety-check queue without booking.', 'Leave the bicycle at the outside rack with a note.', 'Bring it just before closing without an appointment.', '读懂：Repairs taking more than twenty minutes 指超过二十分钟的维修，require an appointment 表示必须预约。随到随查说的是安全检查。\n解析：长时间维修应先预约。直接排免费检查的队不满足维修要求；室外车架被明确说成不是交车点；快关门时直接来，也没有满足预约要求。\n下次：题目给出“耗时很长”等情境时，先把它对应到公告的条件门槛，再执行该条件后的规定。区分服务类别，别把免费检查的办法套给复杂维修。'),
    ]),
    ("Messages about a rehearsal", "Jules: The auditorium is unavailable tonight. Could we rehearse in the music room?\nPriya: The actors fit, but the set does not. We can practice dialogue there.\nJules: Good point. Let's keep tonight's rehearsal and leave the scene changes until Friday.\nPriya: I'll tell the stage crew they needn't come tonight. The actors should still arrive at six.", [
        item("What will happen at tonight's rehearsal?", "Actors will practice their lines.", "The crew will rebuild the set.", "Everyone will rehearse scene changes.", "The group will cancel all practice.", "读懂：音乐教室容得下演员，却放不下布景。practice dialogue 是练习对白；leave the scene changes until Friday 是把换景练习留到周五。\n解析：今晚保留排练，但只练台词。不安排工作人员重搭布景，也不练换景；场地改变并不等于取消全部练习，Jules 明确决定照常排练。\n下次：遇到修改计划的对话，分别记“保留什么、推迟什么、取消什么”。用最后达成的安排作答，不要让最初的场地问题盖过后面已经给出的解决办法。"),
        item("Who is excused from attending tonight?", "The stage crew.", "All the actors.", "Jules and Priya only.", "The music students.", "读懂：they needn't come tonight 是“他们今晚不必来”，这里的 they 指前面的舞台工作人员。随后又说演员仍应六点到。\n解析：被免除今晚出席要求的是舞台工作人员，不是所有演员；对话没有单独豁免 Jules 和 Priya，也没有给音乐学生安排出席任务。音乐教室只是借用场地。\n下次：问谁不用参加时，先找到 needn't 等否定要求，再向前确认代词指谁，并用后一句核对其他人的安排。不要把“在某人的场地”误当成“那类人要参加”。"),
    ]),
    ("Laboratory induction notice", "NEW LAB USERS\nComplete the online safety quiz before booking your in-person induction. Passing the quiz alone does not activate your access card. Card access begins after a technician records your completed induction, normally by the next morning. Students needing access for a Monday class should attend an induction no later than Friday. Bring your student card to the session.", [
        item('Why might a card still fail after the online quiz?', 'The in-person induction has not been recorded.', 'The online quiz must be repeated after every laboratory visit.', 'Cards become active as soon as an induction is booked.', 'Access is activated only after attending the Monday class.', "读懂：Passing the quiz alone does not activate your access card 是“只通过网上测验不会启用门禁卡”。还要完成现场培训，并由技术员登记，通常次日上午生效。\n解析：卡不能用，可能是现场培训尚未登记。材料没说每次进实验室都重考；预约不等于完成培训；也不是等到上完周一的课才激活。\n下次：遇到“已经做了却仍不能用”的题，列出流程各关：通过测验、完成培训、登记、生效。检查尚缺哪一关，别把第一步完成误当成全部完成。"),
        item('What is recommended for a student with a Monday lab?', 'Complete the induction by Friday.', 'Pass the online quiz on Sunday and enter on Monday.', 'Book the induction for Monday after the laboratory class.', 'Attend on Friday but leave before the technician completes the induction.', "读懂：no later than Friday 是“最迟周五”。要在周一上实验课的学生，应在周五或之前参加并完成现场培训，让技术员记录完成情况。\n解析：应最迟周五完成培训。周日只通过网上测验还不够；周一上完课再培训来不及解决进门问题；周五去了却中途离开，也不算完成。\n下次：倒推办事时间时，先找需要使用服务的日期，再考虑前置步骤和处理时间。区分“报名、到场、完成、生效”，尤其不要把到场当作完成全部要求。"),
    ]),
    ("Café menu update", "GARDEN CAFÉ · LUNCH\nSoup and bread $6 · Vegetable bowl $8 · Sandwich $7\nA hot drink is included with any lunch item purchased between 11:30 and 13:00. After 13:00 drinks are priced separately. Bring a reusable cup for a 50-cent discount on a separately purchased drink. Discounts cannot be applied to the lunch package. Please tell staff about allergies before ordering.", [
        item("What is included with a vegetable bowl bought at noon?", "A hot drink.", "A second bowl.", "A reusable cup.", "A sandwich.", "读懂：any lunch item 表示任意一种午餐食品；11:30 到 13:00 之间购买，都会包含一杯热饮。noon 是中午十二点，在这个时段内。\n解析：所以十二点买蔬菜碗会附带热饮。材料没有说送第二碗或三明治；可重复使用的杯子要自己带，它是另一条折扣规则中的物品，不是赠品。\n下次：遇到套餐包含内容的题，先核对购买时间是否落在优惠区间，再找 included 后面的具体物品。把“赠送什么”和“顾客自带什么”分开。"),
        item("When can the reusable-cup discount apply?", "When a drink is purchased separately.", "Whenever a lunch package is purchased.", "Only when ordering soup.", "Only before 11:30.", "读懂：a separately purchased drink 是“单独购买的饮品”。自带可重复使用的杯子，这类饮品可减五十美分；午餐套餐不能用这项折扣。\n解析：条件是饮品单独计价，不是只要买套餐就打折。汤只是菜单中的食品，不决定杯子折扣；文中也没有把优惠限制在十一点半之前。\n下次：判断折扣适用条件时，先找折扣直接修饰的商品，再检查排除条款。不要把套餐供应时段、某个菜名与另一项优惠拼成原文没有的新限制。"),
    ]),
    ("Volunteer river survey", "RIVER WATCH\nVolunteers meet at the footbridge at 8:30 on Sunday. Teams will count litter along assigned sections; do not enter the water. Gloves and collection bags are supplied. Wear sturdy shoes and bring drinking water. The event will be postponed only if a flood warning is issued. A weather update will appear on the club page at 7:00. New volunteers will receive a short briefing before joining a team.", [
        item("What should a volunteer bring?", "Drinking water.", "Collection bags.", "Survey gloves.", 'A map assigning each survey section.', '读懂：Gloves and collection bags are supplied 是“手套和收集袋由组织方提供”；bring drinking water 是“自带饮用水”。活动只在岸边计数垃圾，不准下水。\n解析：选项中需要志愿者自带的是饮用水。收集袋和手套已经提供，不必把它们当作自备要求；虽然队伍有分配好的调查河段，通知没有要求志愿者自备分区地图。\n下次：看活动准备清单，分出“主办方提供”“参加者自带”“禁止做的事”。问要带什么时，直接查自带栏，不要把文中出现的所有用品都算进去。'),
        item("What would cause the survey to be postponed?", "An official flood warning.", "The arrival of new volunteers.", "Cloudy weather alone.", 'A forecast of light rain.', '读懂：postponed only if a flood warning is issued 意思是“只有发布洪水警报，活动才会延期”。天气消息会在七点公布，但公布消息本身不表示取消。\n解析：能导致延期的是洪水警报。新人到场有简短说明会接待，不构成延期理由；仅仅多云不满足条件；小雨预报也不等于已发布洪水警报。\n下次：遇到取消或延期条件，圈出 only if 一类限制词，再逐个核对选项是否满足那个具体条件。不要把一般天气变化扩大成所有活动都不能进行。'),
    ]),
    ("Museum membership message", "Dear member,\nYour annual membership expires on June 30. Renew by June 15 to receive two guest passes for the summer exhibition. Membership prices will remain unchanged this year. Guest passes cannot be used for ticketed evening events. If you renew online, your digital card updates immediately; a printed card can be collected on your next visit. Thank you for supporting our educational programs.", [
        item("Why is June 15 significant?", "It is the deadline for receiving bonus guest passes.", "It is the membership expiration date.", "It is the date prices increase.", "It is the only day printed cards are available.", "读懂：“expires on June 30”是六月三十日到期；“Renew by June 15”是六月十五日前续费。提前续费可获两张展览访客票，所以六月十五日是奖励截止日，不是会员到期日。\n解析：六月十五日重要在于赶上赠票资格。会籍到期是另一个日期；今年价格不变，谈不上当天涨价；纸质卡下次到馆可领，也没有限定只能当天领。\n下次：处理通知中的日期题，为每个日期贴上“到期、优惠、领取”等用途标签。再按题目问的日期找对应事件，避免把提前办理的奖励期限当成服务终止日。"),
        item('According to the message, where is a guest pass explicitly not accepted?', "At a separately ticketed evening event.", "At the summer exhibition during ordinary hours.", "At the museum entrance with a member.", "At a regular educational display.", "读懂：Guest passes cannot be used for ticketed evening events 是“访客票不能用于需另外购票的晚间活动”。赠票本来是为夏季展览提供的。\n解析：因此明确不能用的是另行售票的晚间活动，而不是夏展正常开放时的参观。与会员一起入馆或参观普通教育展览，也都没有被这条规定列为禁用情形。\n下次：做“不适用在哪里”的题，完整保留限制条件：这里同时有“晚间”和“需购票”。只选直接触发限制的情形，不自行增加普通入馆或白天展览的禁令。"),
    ]),
    ("Room exchange messages", "Nora: Could we switch presentation slots? Mine is at 9:00, but my train arrives at 9:20.\nSam: I have the 10:00 slot. I can switch if the instructor agrees.\nNora: She said changes are fine when both speakers email her before Wednesday.\nSam: I'll email her now. Please include me in your message so the details match.", [
        item("What is the reason for Nora's request?", "Her travel schedule conflicts with her presentation.", "She has not completed her slides.", "The instructor canceled the 9:00 slot.", "Sam asked to arrive later.", '读懂：Nora 的展示原定九点开始，她却说 my train arrives at 9:20，即火车九点二十才到。她想与十点展示的 Sam 交换，解决无法按时到场的问题。\n解析：请求的原因是交通时间与展示冲突。没有提到幻灯片没做完；九点时段也没被老师取消；提出换时段的是 Nora，不是 Sam 想晚到。\n下次：问请求的原因时，先找说话人提出请求前后的时间、困难或限制，再与要求完成的事情对照。把“为什么要换”与“老师怎样批准交换”分开，别拿后面的手续当起因。'),
        item('Sam has emailed the instructor, but Nora has not. What is still needed for their proposed switch?', 'Nora must also email before Wednesday.', 'Sam must email, while Nora can confirm after Wednesday.', 'Nora must wait until her train arrives to request the switch.', 'Both must ask the instructor to create a third presentation slot.', "读懂：both speakers email her before Wednesday 是“两名展示者都须在周三之前给老师发邮件”。Sam 已发，不代表两人的义务都完成。\n解析：剩下的是 Nora 也要在周三前发邮件。她不能拖到周三之后；等火车到了再申请不是规定步骤；两人是交换原有时段，无须新建第三个时段。\n下次：处理多人申请规则，先圈出 both，再逐人勾选是否完成，最后核对共同截止时间。题干只更新了一个人的状态时，不要把另一人的必要步骤自动省掉。"),
    ]),
    ("Community garden allocation", "GARDEN PLOT APPLICATIONS\nApplications open March 1 and close March 14. Plots are assigned by lottery, not by application time. Applicants must live in the neighborhood and attend one shared maintenance day each month. Tools may be borrowed during staffed hours. Successful applicants will be contacted on March 20; those not selected will automatically join the waiting list. Please submit only one application per household.", [
        item("Does applying on March 1 improve the chance of getting a plot?", "No, plots are distributed by lottery.", "Yes, the earliest application always wins.", "Yes, early applicants get larger plots.", "No, applications are accepted only on March 14.", "读懂：assigned by lottery 是“用抽签决定分配”，not by application time 是“不按申请时间先后”。申请窗口为三月一日至十四日。\n解析：在三月一日申请不会因更早而增加中签机会。先到先得和早申请能拿更大地块都没有依据；虽然“不增加机会”正确，但说只能三月十四日申请也错，因为窗口有十四天。\n下次：比较竞争资格题的选项时，不只看开头的“是／否”，还要核对后面的理由。先确定分配机制是抽签还是排队，再看日期是否只是受理范围。"),
        item("What happens to an unsuccessful applicant?", "They are added to the waiting list.", "They must submit another application immediately.", 'They must request a place on the waiting list.', "They receive a plot on March 20.", '读懂：those not selected will automatically join the waiting list 意思是“未被选中的人会自动加入候补名单”。候补是等待将来可能空出的名额，不是已分到地块。\n解析：落选者会进入候补，无须立即重新申请；每户本来也只许交一份。加入候补是自动完成的，也不用再提出入列申请；三月二十日是通知成功申请者的日期，不保证落选者当天获地。\n下次：遇到申请结果题，区分“获批、候补、需重申”三种状态，并注意 automatically 说明哪一步由系统或组织方直接完成。'),
    ]),
    ("Career clinic appointment", "Subject: Your career clinic appointment\nYour consultation is confirmed for Thursday at 14:15 in Room 204. Please upload your résumé at least one day beforehand so the adviser can review it. If you only want a photograph for your profile, visit the separate drop-in desk on Friday; this appointment is for résumé and interview advice. Cancellations made less than two hours before the meeting may limit your ability to book another session this month.", [
        item('When should the résumé be uploaded?', 'By Wednesday at 14:15.', 'By Thursday at 12:15.', "At the beginning of Thursday's consultation.", 'Before visiting the Friday photograph desk.', "读懂：预约在周四十四点十五分；at least one day beforehand 是“至少提前一天”。简历须让顾问提前阅读，所以最迟周三十四点十五分上传。\n解析：周四十二点十五分仅提前两小时，那是取消预约规则中的时长，不是交简历的期限；咨询开始时才交太晚；周五拍照属于另一项服务。\n下次：有多个时间要求时，先把每个时长和对应动作配对，再从活动时间倒推。这里“一天”管上传，“两小时”管取消，不能见到同一封邮件就混用。"),
        item("What is the purpose of Thursday's appointment?", 'To discuss a résumé and interview preparation.', 'To have a profile photograph taken during a booked session.', 'To upload a résumé without discussing it with an adviser.', 'To receive only advice about canceling appointments.', "读懂：consultation 是咨询会面；邮件说本次是 résumé and interview advice，即简历与面试方面的指导。拍个人资料照片要去周五另设的随到随拍服务台。\n解析：周四预约用于讨论简历、准备面试，不是拍照。上传简历只是会面前的准备，不是见顾问的全部目的；取消规定是提醒，也不是预约要谈的唯一内容。\n下次：判断预约目的，先找“这次会面是做什么”的总说明，再把会前准备、其他服务和取消政策分开。不要让某项手续取代预约本身的用途。"),
    ]),
    ("Shuttle service change", "CAMPUS SHUTTLE · WEEKEND DIVERSION\nOn Saturday and Sunday, the shuttle will use River Road while Oak Street is resurfaced. The museum stop will be closed. Passengers for the museum should use the temporary stop outside the post office, a five-minute walk away. Departure times and fares are unchanged. Regular service resumes Monday unless roadwork is delayed; updates will appear in the travel app.", [
        item("Where should museum passengers get off this weekend?", "At the temporary post office stop.", "At the closed museum stop.", "At the roadwork entrance.", "At a new stop inside the museum.", '读懂：周末因 Oak Street 修路，博物馆站关闭。公告让去博物馆的乘客改用邮局外的 temporary stop（临时站），再步行五分钟。\n解析：应在邮局临时站下车，不能继续用已关闭的博物馆站；修路入口不是指定下车点；馆内新站也没有出现在安排中。River Road 是改道经过的道路，不是题目所问的下车站名。\n下次：改线通知常同时出现道路、关闭站和替代站。先确定自己的目的地，再找针对该目的地的 should use 等指令，最后核对是否还需步行。'),
        item("Which part of the service remains the same?", "The departure timetable.", "The route along Oak Street.", "The location of every stop.", 'The Monday restart, even if the roadwork is delayed.', '读懂：Departure times and fares are unchanged 是“发车时间和票价不变”。变化的是周末行车路线与博物馆站的使用安排。\n解析：选项中保持不变的是发车时刻表。车辆不再沿 Oak Street 行驶；博物馆站由临时站替代，不能说所有站点位置不变。周一恢复还附有修路不延误的条件，不能说无论如何都在周一恢复。\n下次：问什么不变时，先找 unchanged 等明确标记，再与 changed 的事项分栏。题干要的是被确认保留的安排，有附加条件的计划日期不能当成无条件承诺。'),
    ]),
    ("Archive access instructions", "SPECIAL COLLECTIONS\nReaders must request archival boxes by 15:00 on the working day before their visit. Photography without flash is allowed unless an item's label states otherwise. Bags and pens must remain in the lockers; pencils are provided. Only one folder may be open at a time. Staff will explain how to support fragile pages. Digital copies of frequently requested material are available without a reading-room appointment.", [
        item('What should a reader do before visiting?', "Request boxes by the previous working day's deadline.", 'Request boxes at 15:00 on the day of the visit.', 'Bring pens to label each folder before opening it.', 'Book an appointment even when using only available digital copies.', "读懂：the working day before their visit 是“参观前一个工作日”，而不是参观当天。调阅档案箱要在那天下午三点前提出申请。\n解析：到馆前应按这个期限申请箱子。当天下午三点才申请太晚；笔必须放在储物柜里，不能拿来标注文件；只用已有数字副本则不必预约阅览室。\n下次：读档案馆等办事规则时，分清“申请实物”“预约到馆”“使用电子材料”。遇到 working day，按工作日倒推，不能把周末或当天直接当作符合期限。"),
        item('A reader wants material available as digital copies and also wants to inspect an original box on Tuesday. Which plan follows the instructions?', "Read the digital copies without booking and request the box by the previous working day's deadline.", 'Read the digital copies immediately and request the box before 15:00 on Tuesday.', 'Request the box before visiting and wait for its arrival before opening the digital copies.', 'Book the digital copies for Tuesday and request the box when arriving that morning.', '读懂：“without a reading-room appointment”是“不用预约阅览室”；实物箱则要在到访前一个工作日十五点前申请。两种材料的手续不同。\n解析：可直接读数字副本，并提前申请箱子。周二才申请，不论是早上还是十五点前，都过了前一个工作日的期限；数字副本不需另约，也不用等箱子送到才看。\n下次：同时用电子版和原件时，各列一条办理流程，再检查选项是否都满足；尤其把“当天十五点”与“前一工作日十五点”分开。'),
    ]),
    ("Apartment viewing message", "Hello,\nThe apartment viewing will be from 17:00 to 18:00 on Tuesday. Please use the courtyard entrance because the front stairs are being repaired. The advertised rent includes water but excludes electricity and internet. We cannot accept an application until you have viewed the property, although you may bring the documents with you. If Tuesday is impossible, reply with two alternative times and we will try to arrange a separate visit.", [
        item("Which expense is included in the rent?", "Water.", "Electricity.", "Internet.", "All household expenses.", "读懂：rent includes water 是“房租含水费”，excludes electricity and internet 是“不含电费和网费”。includes 与 excludes 的方向相反。\n解析：已包含的支出是水费。电费、网费被明确排除；“所有家庭支出”把仅有的一项扩大成了全部，和排除条款直接冲突。不要因为这些账单都与住房有关就认为房租全包。\n下次：费用题先按 includes 与 excludes 划出两栏，再把选项逐项放进去。遇到 all 之类全包说法，用任意一项明确不包含的费用就能排除。"),
        item("An applicant cannot attend Tuesday's viewing but has all the documents ready. What should they do before applying?", 'Arrange another viewing by proposing two possible times.', 'Send the documents now and view the apartment after approval.', 'Choose Wednesday and arrive without waiting for a reply.', 'Ask to replace the required viewing with an advance rent payment.', "读懂：房东说看过房才能接受申请，文件齐全也不能替代看房。若周二不行，应回复两个可行时段，房东会尝试另约。\n解析：所以应先提出两个时间安排另一次看房。先交材料等批准后再看，颠倒了条件顺序；直接周三到场没有确认；预付租金代替看房也不是房东允许的办法。\n下次：题目同时给出“准备好了什么”和“还做不到什么”，先找必须满足的前置条件。对 we will try 一类表述，要区分提出备选时间与预约已经确认。"),
    ]),
    ("Language exchange bulletin", "LANGUAGE EXCHANGE\nPairs meet for forty minutes each week, spending equal time in each language. This is conversation practice, not a correction service for assessed coursework. Beginners are welcome. Complete the interest form by September 12 and list at least three available times. Matching depends on schedules and language preferences, so submitting a form does not guarantee a partner. Unmatched applicants may join our open conversation circle.", [
        item("How much of a standard meeting is devoted to each language?", "Twenty minutes.", "Ten minutes.", "Thirty minutes.", "Forty minutes.", "读懂：每周一次会面总共四十分钟，spending equal time in each language 是“两种语言用同样长的时间”。四十分钟是总时长，不是每种语言各四十分钟。\n解析：四十除以二，每种语言二十分钟。十分钟加起来只有二十分钟；三十分钟加起来要一小时；每种四十分钟则要八十分钟，都与总时长不符。\n下次：读时间分配题，先确定给出的数字是总量还是单项，再找 equal 等分配规则。算完用各部分相加检验，确保没有把总时长重复算给每一项。"),
        item('What alternative is offered if a partner cannot be found?', 'An open conversation circle.', 'A partner with guaranteed matching availability.', 'An individual session correcting assessed essays.', 'Priority registration for the next language course.', "读懂：submitting a form does not guarantee a partner 是“交表不保证配到伙伴”。没有配成对的申请者，可以参加开放式的会话小组。\n解析：替代方案是参加开放会话圈，而不是一定再安排时间匹配的搭档。活动明确不是批改计分作业的服务；下次语言课优先报名也没有被提供。\n下次：遇到“未成功时怎么办”，先找到 unmatched 等表示失败状态的词，再读紧随其后的替代方案。不要把原目标当成仍然保证实现，也别加入材料没有承诺的补偿。"),
    ]),
    ("Equipment return reminder", "Subject: Return your field sensor\nYour sensor is due at the geography office by 16:00 on Friday. Please export your measurements before returning it; devices are cleared when checked in. If the office is closed unexpectedly, use the secure return drawer beside Room 12 and email the device number. Do not use the library's book-return slot. Late returns may prevent the next field team from collecting its equipment.", [
        item('Why should students export their measurements?', "The device's data will be erased at check-in.", 'The exported file is needed to extend the return deadline.', 'The exported file replaces the required device-number email.', 'The drawer can accept sensors only after the library closes.', '读懂：export your measurements 是“把测量数据导出保存”；devices are cleared when checked in 是“设备交还登记时会被清空”。所以要在归还前留好自己的副本。\n解析：导出的原因是设备数据会被删除，导出文件并不能延长归还期限。导出文件不能替代异常关门时发送设备编号的邮件；归还抽屉能否使用也不取决于图书馆何时关门。\n下次：问操作原因，先寻找紧接操作后的后果或理由，再判断该操作如何避免损失。把保存数据、告知设备编号、选择归还地点三个目的分开。'),
        item("The office closes unexpectedly on Friday afternoon. Which action both meets the alternative return procedure and protects the student's work?", 'Export the measurements, use the secure drawer, and email the device number.', 'Export the measurements and leave the sensor in the library return slot.', 'Use the drawer and leave the measurements on the device as the only copy.', 'Export the measurements but keep the sensor until the office reopens.', "读懂：“export your measurements”是导出测量数据；“devices are cleared”说明归还时设备会被清空。办公室意外关门则改用十二号房旁的安全归还抽屉，并邮件告知设备编号。\n解析：完整做法是先导出、再用指定抽屉、再发编号邮件。图书馆还书口明确不能用；只留设备内一份数据会丢失；等重新开门再还，则没有按备用流程及时归还。\n下次：题干同时要求“遵守流程”和“保护成果”时，拆成两个检查项，再核对选项是否全做到。找到备用地点并不意味着备份和通知这两步可以省略。"),
    ]),
    ("Film society schedule", "FILM SOCIETY · SEPTEMBER\nSept 5: Silent film with live piano, 19:00\nSept 12: Documentary and director conversation, 18:30\nSept 19: Student short films, 19:00\nSept 26: Outdoor screening, sunset\nIndoor events are in the Arts Theatre. The outdoor event moves indoors if rain is forecast by noon. Tickets for the documentary include the conversation; it cannot be booked separately. Student filmmakers attend the September 19 event free.", [
        item("Which event includes a discussion with its director?", "The September 12 documentary.", "The September 5 silent film.", "The September 19 student films only.", "The September 26 screening only.", "读懂：九月十二日安排 Documentary and director conversation，即“纪录片放映及与导演交流”。后面还说明纪录片票已包含交流环节，不能单独预订。\n解析：带导演讨论的是十二日的纪录片。五日是钢琴现场伴奏的默片；十九日是学生短片；二十六日是户外放映，这些活动都没有被标注导演交流。\n下次：日程匹配题先找题目指定的活动特色，再横向读出同一行的日期与片目。别因某场有创作者参加或有特殊形式，就自行补上节目表没写的讨论。"),
        item("What will happen if rain is forecast for September 26 by noon?", "The screening will be held indoors.", 'The outdoor screening will be postponed to the next evening.', "The screening will start at noon.", "The documentary discussion will be free.", '读懂：The outdoor event moves indoors if rain is forecast by noon 是“若中午前的预报显示会下雨，户外活动改到室内”。受影响的是九月二十六日那一场。\n解析：放映会转为室内，并没有推迟到第二天晚上。noon 是查看预报的时间界限，不是放映开始时间；纪录片交流属于十二日，与本次改场地和是否免费无关。\n下次：遇到天气预案，用“触发条件—调整对象—调整内容”三步整理。特别区分查看预报的时间与活动时间，别把改地点扩大为取消或改票价。'),
    ]),
    ("Message about peer review", "Tariq: Are we supposed to edit every sentence of our partner's draft?\nElena: No. The instructions ask us to comment on the argument and organization first.\nTariq: I found a weak example in paragraph three.\nElena: That's exactly the kind of thing to mention. Add a suggestion, not just a criticism. We can flag repeated grammar problems afterward.\nTariq: I'll explain why the example doesn't support the claim.", [
        item('What should the reviewers prioritize?', 'The argument and organization.', 'Sentence-level corrections before considering the argument.', 'The number of examples regardless of their relevance.', 'A replacement topic before evaluating the existing draft.', "读懂：argument and organization 是“论点与文章组织结构”。Elena 说先评论这两方面，反复出现的语法问题可以 afterward，也就是之后再标出。\n解析：优先关注内容论证和结构，不是先逐句改语法。提到第三段例子弱，是说它支持不了论点，不是只数例子多少；也没有要求先换掉整篇文章的主题。\n下次：问优先顺序时，抓住 first、afterward 等词，把各项任务排好。讨论某个例子时，还要判断它为何被提及：证据的作用比数量更关键。"),
        item('What does Elena recommend adding to criticism?', 'A suggestion for improvement.', 'A final grade based mainly on grammar.', 'A replacement claim without explaining the weakness.', 'A request to remove the paragraph without proposing an improvement.', "读懂：Add a suggestion, not just a criticism 是“除了指出问题，还要提出改进建议”。Tariq 找到例子不能支持论点的问题，Elena 希望反馈能帮助修改。\n解析：应在批评后补上改进办法。按语法打总分不等于提供建议；不解释弱点就换主张，不能让作者明白原因；只要求删段落却不提出改善方向，仍是不完整的反馈。\n下次：问对方建议增加什么，先找 add、not just 后的对比。把“发现问题”“解释原因”“建议怎样改”分开，选补足反馈作用的那一步。"),
    ]),
    ("Reuse store collection policy", "CAMPUS REUSE STORE\nDonate clean household items on Wednesday afternoons. We accept lamps only if they work and have an intact cable. Mattresses and food cannot be accepted. Students may reserve a donated item online, but must collect it within two working days. Items not collected in time become available to others. Volunteers can help carry heavy items to the curb; transport beyond the curb must be arranged by the recipient.", [
        item("Which donation would meet the policy?", "A working lamp with an undamaged cable.", "An unopened mattress.", "A bag of fresh food.", "A lamp with a broken cable.", "读懂：灯具只有能正常工作，并且电线完好，才会被接受。intact cable 是“没有破损的电线”；床垫和食物则属于不接收的类别。\n解析：符合条件的是功能正常且电线无损的灯。床垫未拆封也不改变类别限制；食物新鲜也仍被排除；电线坏了的灯不满足两项必要条件中的一项。\n下次：判断捐赠是否合规，先查类别是否允许，再逐项检查该类别的附加条件。对 and 连接的要求必须同时满足，不要用“很新、很干净”抵消明确的禁收规则。"),
        item('A student reserves a heavy item but cannot arrange transport until the following week. What should they understand?', 'The recipient must arrange transport and collect the item within two working days.', 'Volunteers will complete the delivery once they have carried the item to the curb.', 'The recipient has two working days to donate an item before collecting the reserved one.', 'The store will keep the reservation until the recipient has arranged personal transport.', '读懂：“within two working days”是两个工作日内；逾期未领的物品会重新开放。志愿者可搬到“the curb”（路边），之后的运输由领取者自己安排，不能因此延长预留时间。\n解析：等到下周不一定仍能保留，且没有送货保证。志愿者不会因搬到路边就继续送到家；两日规定管的是预订后的领取，也没有要求先捐一件才能领另一件；网上预订也不能无限延长保留期。\n下次：处理取物计划，分开核对“最迟何时取”和“谁负责哪段运输”。物品沉重或个人没车不会自动取消期限，也不会扩大志愿者承诺的帮助范围。'),
    ]),
]

ACADEMIC_PASSAGES = [
    ("The value of urban wetlands", 'Urban wetlands are sometimes described as unused land because they cannot easily support buildings. This description overlooks the work they perform. During heavy rain, a wetland can hold water temporarily and release it slowly, reducing the speed at which runoff reaches a river. Plants and sediments may also trap some pollutants, although this capacity is limited and does not make wetlands a substitute for preventing pollution.\n\nWater storage and pollution removal are useful even when a site is not visually impressive. [A] Restoration projects often aim to recover these functions. [B] Yet reproducing the appearance of a wetland is easier than rebuilding its hydrology, the pattern of water movement that sustains it. A pond surrounded by suitable plants may still fail if its water level remains constant while the organisms require seasonal fluctuations. Engineers and ecologists therefore monitor water levels as well as vegetation.\n\nEvaluating success also requires patience. [C] The different rates of change mean that relying only on the faster response can lead to premature claims. [D] The strongest assessments compare several indicators over time and recognize that restored wetlands may provide valuable services without becoming exact copies of the systems that existed before urban development.', [
        item('What is the passage mainly about?', 'Wetland functions and the challenges of restoring them.', 'Why urban wetlands should be evaluated by their appearance.', 'How attracting birds can replace the need to monitor water.', 'Why restored wetlands must duplicate earlier ecosystems to be useful.', '读懂：文章先说湿地可暂存雨水、减缓径流，也能有限地截留污染物；随后解释恢复 hydrology（维持湿地的水流规律）比做出湿地外观更难，评估还要长期看多项指标。\n解析：主旨是湿地的作用及恢复这些作用的困难。只凭外观评价与原文相反；吸引鸟类不能代替水位监测；结尾也明确说不必完全复制从前的生态系统，仍可能有价值。\n下次：学术主旨题先给每段写一个短标签，再找能覆盖整条思路的选项。特别用结论核对 must 等绝对要求，别把例子或被反驳的观点当主旨。'),
        item('How can wetlands reduce rapid runoff?', 'By temporarily storing water and releasing it gradually.', 'By increasing water speed through newly planted channels.', 'By holding the water level constant throughout the year.', 'By filtering pollutants before allowing rain to enter rivers.', "读懂：hold water temporarily and release it slowly 是“暂时蓄住水，再慢慢释放”。雨水到河流的速度因此减慢，这才是减缓径流的机制。\n解析：答案是暂存后逐步放水。让水加速与效果相反；全年保持水位不变属于后文可能导致恢复失败的情形；过滤污染物是另一项作用，不是减慢水流的这条因果链。\n下次：题目问如何产生某种效果时，用“动作→直接结果”复原机制。若文中列了多种功能，逐项分开，不能把净水作用拿来替代蓄水作用的解释。"),
        item('Why might a planted pond fail as a restoration project?', "Its water pattern may not meet organisms' needs.", 'It attracts birds before its plants reach their mature height.', 'Its vegetation differs slightly from the original wetland.', 'It stores water temporarily instead of keeping a stable level.', "读懂：hydrology 指维持湿地的水流运动规律。有些生物需要水位随季节涨落；即使池塘周围植物合适，水位一直不变仍可能让修复失败。\n解析：问题在于水文条件不合生物需要，而非鸟先来、植物尚未长高；也不是外观与旧湿地稍有不同就失败。暂存雨水本是湿地的有益功能，不应反说必须保持恒定水位。\n下次：遇到“看起来合格却失败”的题，找外观条件与实际功能之间的转折，再追踪生物或系统真正需要什么。不要把原文指出的缺陷当成解决办法。"),
        item("The word 'premature' most nearly means", 'made before enough time has passed.', 'made after sufficient time has passed.', 'made independently of earlier assessments.', 'made only when several indicators agree.', "读懂：前句说评估成功要有耐心，后面说只看较快出现的变化，会导致 premature claims，也就是证据尚未等充分就急着下结论。\n解析：premature 在这里指“时间还不够就作出的”，不是等了足够久才作出。独立于先前评估说的是评估之间的关系；多个指标一致说的是证据条件，都不是这个词强调的过早。\n下次：词义题先找前后句的时间线或褒贬态度，再把候选意思代回。这里 patience 与只看 faster response 形成对比，能锁定“太早”，无需记专业湿地知识。"),
        ('Where would the following sentence best fit in the passage?\n\nA newly restored site may attract birds quickly, while changes in soil processes take years.', ['Position [A]', 'Position [B]', 'Position [C]', 'Position [D]'], 2, "读懂：待插句说新修复湿地可能很快吸引鸟类，但土壤过程的改变要多年；这是两种恢复速度的对比。\n解析：选 Position C：前句说评估要耐心，插句解释原因；后句的 different rates 指这两种速度。Position A、Position B 仍在讲功能或水文，插入会打断；Position D 太晚，使前句先谈速度差却没有先说明两类变化。\n下次：插句题同时查前后衔接：前句是否提出需要解释的观点，后句是否用概括词回指插句。这里“需要耐心→快慢例子→不能只看快变化”才是完整顺序。"),
    ]),
    ("Why borrowed words change", "When a language adopts a word from another language, it rarely preserves every feature of the original. Speakers may adjust unfamiliar sounds to fit their existing sound system. They may also change the word's grammatical behavior so that it follows ordinary patterns for forming plurals or indicating tense. These adjustments allow a borrowed expression to function within its new linguistic setting.\n\nMeaning can change as well. A word with a broad meaning in the source language may be used for a narrow category in the borrowing language. For example, the name of a general cooking method could become associated with one particular dish. Such changes do not necessarily result from misunderstanding. They may reflect the specific context in which speakers first encountered the term.\n\nConsider a borrowed noun used in a shop sign. If local speakers add their usual plural ending, a customer can recognize that the sign names several items even without knowing how plurals are formed in the source language. The change links an unfamiliar root with a familiar grammatical cue. Borrowing can thus expand a vocabulary while preserving many of the receiving language's ordinary patterns.", [
        item('What is the main idea?', 'Borrowed words are reshaped to work within the language that adopts them.', 'Borrowed words must preserve their original sounds before they can be used.', 'Changes in borrowed words mainly result from errors by bilingual speakers.', 'Borrowing new vocabulary requires a community to replace its own grammatical system.', "读懂：borrowed words 是“外来词”。文章依次讲声音、语法和词义的调整，再用商店标牌说明熟悉的词尾怎样帮助理解新词。\n解析：共同点是让外来词适应接收它的语言。声音可以调整，不必原样保留；词义变化不一定是错误；采用本地复数词尾也不等于替换整套语法。\n下次：遇到多种变化的主旨题→找各段变化共同服务的目的→检查选项是否同时覆盖声音、语法和意义。"),
        item("Why might speakers alter a borrowed word's pronunciation?", 'To fit sounds already used in their language.', "To retain the original language's rules for forming plurals.", 'To give a term a narrower meaning than it originally had.', 'To mark it as belonging to a foreign grammatical system.', "读懂：adjust unfamiliar sounds to fit their existing sound system 是“调整不熟悉的声音，让它符合自己语言已有的发音体系”。这里的调整对象是声音。\n解析：改发音是为了适应本族语言已有的声音。复数构成属语法，不是发音目的；缩小词义是另一个变化；突出外来语法体系也与融入新语言环境的方向相反。\n下次：题目问某一种变化的原因时，先锁定变化对象：声音、语法还是意义。即使几个选项都与借词有关，也必须与题干指定的那一类变化直接对应。"),
        item('What does the cooking example illustrate?', 'A broad meaning can become more specialized.', 'A change in pronunciation can prevent a change in meaning.', 'Speakers may restore the original general meaning of a term.', "A word's grammatical behavior determines how it reaches a community.", "读懂：“a general cooking method”是一般烹饪方法，“one particular dish”是某一道特定的菜。原来涵盖一种做法的词，借入后只指一道菜，说明词义范围缩小。\n解析：它说明宽泛词义可以专门化，而不是发音变化阻止了词义变化。把特殊用法恢复为一般意义，方向正好相反；语法如何决定传播路线也不是这个例子讨论的问题。\n下次：问举例作用，先读例子前的总述，再把例子压缩成“原来是什么→后来是什么”。同时核对变化的对象和方向，别只因选项出现语言学术语就选它。"),
        item('Which new situation follows the principle illustrated by the shop-sign example?', 'Speakers add a familiar tense ending to a borrowed verb to show when an action happened.', "Speakers infer a borrowed noun's exact meaning only from the number of letters in it.", 'Speakers preserve every foreign sound before placing a borrowed word in a sentence of their own language.', 'Speakers use a foreign plural ending to show that local grammatical rules cannot apply to borrowed words.', "读懂：usual plural ending 是“惯用的复数词尾”，可让人知道标牌说的是多个物品。题目要把“新词＋熟悉语法提示”的原理用到另一情境。\n解析：给借来的动词加熟悉的时态词尾，也是在用本地语法说明动作时间。字母数量不能给出精确词义；声音不必全部保留；原文展示的正是本地规则能作用于外来词。\n下次：遇到原理应用题→先抽出原例的关系，再换对象核对→检查新例是否仍用熟悉的语法提供信息，而非只重复话题词。"),
        item("The word 'encountered' in paragraph 2 most nearly means", 'came into contact with.', 'made incorrect use of.', 'changed the grammatical form of.', 'stopped communicating through.', "读懂：first encountered the term 是“第一次接触这个词”。那次接触发生的具体情境，可能影响后来怎样使用它。\n解析：这里指接触到，不是误用、改语法形式或停止通过它交流。前句还说词义缩小不一定源于误解，因此不能把接触直接等同于用错。\n下次：词义题→先确定句子讲的是接触、修改还是判断→把候选意思放回前后句，检查是否增加了原文没有的错误或停止含义。"),
    ]),
    ("Measuring a glacier", 'A glacier can lose mass even while its front edge advances. This apparent contradiction arises because the position of the edge depends on both melting and the movement of ice from farther uphill. A temporary increase in ice flow may push the front forward while the glacier as a whole becomes thinner. Consequently, photographs of the front alone cannot establish whether the entire glacier is gaining or losing ice.\n\nThe problem is therefore one of measuring the whole body of ice rather than only its most noticeable boundary. [A] To estimate mass change, researchers combine several measurements. Stakes placed in the surface reveal local accumulation and melting. Satellite observations can show changes in height over a much larger area. Each method has limitations: stakes cover only small locations, while satellite measurements may be affected by clouds or uncertainty about the density of snow.\n\n[B] Agreement between independent methods increases confidence, but disagreement can also be informative. [C] A heavy snowfall, for instance, can temporarily increase surface height without reversing a long-term loss of ice. [D] Scientists therefore distinguish short-term variation from persistent trends and avoid treating a single season as a complete description of the system.', [
        item('Why can a glacier advance while losing mass?', 'Ice flow can move its front forward despite overall thinning.', 'A forward-moving edge shows that accumulation exceeds melting overall.', 'Ice density increases whenever the front edge moves forward.', 'Uphill flow slows while fresh snowfall thickens the whole glacier.', "读懂：“front edge advances”是前缘向前推进，“becomes thinner”是冰体变薄，两者可以同时发生。上游冰流加快可暂时把前缘推向前，但整条冰川仍在损失冰量。\n解析：所以“前进”与“总量减少”可以同时发生。前缘前进不证明积累超过融化；文中没说冰密度必然上升；冰流减慢、降雪让全体变厚也不是这里给出的机制。\n下次：遇到看似矛盾的现象，先检查两项描述是否测量同一件事。这里一个是边缘位置，一个是总冰量；分开各自成因，就不会把局部移动误判为整体增长。"),
        item('What is one limitation of surface stakes?', 'They provide information from relatively few locations.', 'Their estimates depend mainly on cloud-free satellite images.', 'They cannot record both accumulation and melting at the same site.', 'They represent total mass more directly than local surface changes.', "读懂：表面标杆能显示当地的积雪增加与融化，但 stakes cover only small locations，意思是“标杆只覆盖很小的局部位置”，不能单凭它概括整条冰川。\n解析：局限是测量地点的覆盖有限。受云层影响是卫星观测的问题，不是标杆的主要限制；原文说标杆能显示积累和融化；它也不比局部变化更直接代表总冰量。\n下次：比较测量方法时，按“方法—能测什么—局限”逐行配对。选项把另一种方法的弱点搬过来，或把局部测量说成全体结果，都要排除。"),
        item('Why does the author mention heavy snowfall?', 'To distinguish a temporary height increase from long-term recovery.', 'To explain why a height increase must indicate faster ice flow.', 'To show why density can be ignored after a large storm.', 'To demonstrate that local stakes cannot detect new accumulation.', "读懂：“temporarily increase surface height”是暂时抬高表面；“without reversing a long-term loss of ice”是不扭转冰量长期减少。大雪后的高度上升，不等于冰川整体已恢复。\n解析：例子用于区分短期升高与长期恢复，不是说升高必因冰流加快。文中也未说大雪后可以忽略密度；标杆能观察当地积累，所以“不能发现新增积雪”不符合前文。\n下次：问例子的作用，先找例子中的对比，再看它支持哪条概括。这里是“暂时升高／长期流失”，不要改成“冰流快慢”或“仪器不能测”的别种关系。"),
        item("The word 'persistent' most nearly means", 'continuing over time.', 'changing at regular intervals.', 'restricted to particular locations.', 'occurring without an identifiable cause.', "读懂：末句要求区分 short-term variation，即短期波动，与 persistent trends，即持续一段时间的趋势；不能用一个季节概括整个系统。\n解析：persistent 在这里是“随时间持续的”。规律性地间隔变化强调周期，不等于持续；局限在某些地点讲空间；没有可识别原因讲成因，都偏离这里的时间对比。\n下次：词义题遇到 distinguish 等区分词，把两边放在同一维度比较。这里一边是短期变化，另一边就应是长期持续，而不是地点、原因或周期。"),
        ('Where would the following sentence best fit in the passage?\n\nIt may expose an error, or it may indicate that an unusual event affected only part of the glacier.', ['Position [A]', 'Position [B]', 'Position [C]', 'Position [D]'], 2, "读懂：待插句说“它”可能暴露错误，也可能说明异常事件只影响冰川的一部分。先要找清 It 指什么。\n解析：选 Position C：前句刚说不同方法结果不一致也有用，It 就回指这种不一致；后句的大雪是异常事件的例子。Position A、Position B 都还没介绍结果不一致，指代无着落；Position D 已在例子后，破坏“总体解释→具体例子”的顺序。\n下次：遇到以代词开头的插句，先找紧邻的明确先行词，再看后文的 for instance 是否正好举例说明插句，两边都接上才确认位置。"),
    ]),
    ("How markets share information", "Prices can communicate information without explaining its cause. When the supply of a product falls, a higher price may encourage consumers to use less and producers to offer more. Neither group must know precisely why the supply changed in order to respond. Economists often describe this process as a way of coordinating decisions among people who possess different pieces of information.\n\nHowever, the signal is incomplete. A price may fail to reflect costs imposed on people who are not involved in the transaction. If a factory pollutes a river, the downstream community may bear a cost that is absent from the product's market price. Consumers then receive a misleading picture of the resources used to produce it.\n\nPolicies such as pollution charges attempt to bring some of these external costs into decision making. Their effectiveness depends on measurement and implementation, not simply on announcing a charge. A fee too small to influence behavior may raise revenue without reducing damage. The broader lesson is that prices can organize activity efficiently in some circumstances while requiring additional institutions and information in others. Recognizing both their strengths and their limits is essential when comparing policy options.", [
        item('What is the main purpose of the passage?', 'To explain both the information conveyed by prices and its limitations.', 'To show how higher prices directly reveal the causes of shortages.', 'To compare pollution charges mainly in terms of the revenue they raise.', 'To explain why market signals make additional institutions unnecessary.', "读懂：第一段说价格能促使买卖双方调整行动；后文转而指出，价格可能漏掉污染等由外人承担的成本，需要额外制度和信息补足。\n解析：主旨是价格传递的信息及其局限。价格不直接揭示短缺原因；污染收费只是补充说明，不是全文主要比较收费收入；认为市场信号使其他制度多余，与结尾相反。\n下次：主旨题遇到 However，分别概括转折前的作用和转折后的限制。选能把两面连起来的答案，不要只抓某个收费例子，或只肯定市场而漏掉作者的保留。"),
        item('What may a higher price encourage consumers to do?', 'Use less of a product.', 'Seek a larger quantity before prices stabilize.', "Treat downstream pollution as part of the product's price.", 'Wait to respond until the cause of the shortage is known.', "读懂：供给减少时，更高价格可能鼓励 consumers to use less，也就是让消费者少用；同一句对生产者说的则是多提供一些。\n解析：消费者的反应是减少使用，不是趁稳定前多买。下游污染成本可能根本没体现在价格中；人们也不必先知道短缺原因才行动，原文明确说不用知道得很精确。\n下次：一个句子涉及多类人时，分别配对“谁—采取什么行动”。题目问消费者就只沿消费者那条线推理，别混入生产者反应，也别把后文的污染问题当成当前机制。"),
        item('Why is the river example included?', 'To illustrate a cost missing from a market transaction.', 'To illustrate a production expense already paid by the factory.', 'To show how consumers directly compensate a downstream community.', 'To explain why reduced supply necessarily increases river damage.', "读懂：“downstream community”是下游居民；“absent from the product's market price”是未计入产品市场价。居民并非买卖双方，却承担河流污染损失，说明价格可能漏掉第三方成本。\n解析：河流例子说明价格漏计了外部承担的成本。不是工厂已付清的生产费用；也没有消费者直接赔偿居民的安排；更未建立“供给减少必然增加河流污染”的因果关系。\n下次：分析成本类例子，列出“谁造成、谁受损、谁实际付钱”，再看损失是否反映在交易价格中。不要把有人承担损失误读成生产者或消费者已经补偿了损失。"),
        item('According to the passage, what may happen if a pollution fee is too small to influence behavior?', 'It may collect money without changing production choices.', 'It will reduce damage even if production remains unchanged.', 'It can remove the need to estimate the external cost.', 'It mainly succeeds by telling consumers why supply has changed.', "读懂：A fee too small to influence behavior 是“费用低到不足以影响行为”。它可能增加收费收入，却没有减少污染损害。\n解析：因此很小的污染费可能收到了钱，却没让生产选择改变。不能保证生产不变也会减害；收费效果仍依赖测量与执行，不能省掉成本估计；解释供给变化原因也不是这项费用的作用。\n下次：政策效果题分开看“有没有实行措施”“有没有改变行为”“有没有达到目的”。有收入不等于有环保成效，遇到 may 要保留可能性，别改成必然成功。"),
        item("In this passage, 'coordinating' most nearly means", 'bringing separate actions into a working relationship.', 'determining the original causes of separate events.', 'combining records into a single historical account.', 'setting identical objectives for different participants.', "读懂：价格上涨时，消费者可能少用、生产者可能多供应；他们不必拥有同样的信息，也能调整彼此相关的决定。这就是文中的 coordinating。\n解析：它指“让分散的行动配合起来”，不是找出事件最初原因，也不是汇编历史记录。消费者与生产者的行动不同，所以也不要求所有参与者设定完全相同的目标。\n下次：抽象词义题先把作者紧邻的具体例子讲成白话，再反推那个词概括什么。这里看的是各方行动如何相互配合，而不是各方是否知道同一原因或追求同一目标。"),
    ]),
    ("The timing of bird migration", "Migration is often described as a response to falling temperatures, but many birds begin moving before the weather becomes cold. Changes in day length provide a more predictable seasonal signal than a single warm or cold day. Internal biological rhythms interact with these signals to prepare birds for a journey, influencing feeding behavior and the storage of energy.\n\nLocal conditions still matter. A bird ready to migrate may delay departure when strong winds would make flight costly. Once conditions improve, it can begin its journey quickly. Thus the seasonal preparation and the immediate decision to depart occur on different time scales. Confusing them can make migration appear less organized than it is.\n\nClimate change complicates this relationship. The timing of food availability at a destination may shift more rapidly than the day-length cues used far away. Birds arriving according to an established schedule could then miss the period when food is most abundant. Some populations adjust their timing, but the ability to do so varies. Researchers compare arrival dates, food peaks, and breeding outcomes to determine whether an earlier arrival represents a successful adjustment rather than merely a change in the calendar.", [
        item('What is the passage mainly concerned with?', 'Different signals and time scales that influence migration.', 'How day length determines the exact departure date of every bird.', 'Why destination conditions replace internal rhythms before departure.', 'How short-term weather alone explains successful migration.', "读懂：“day length”是日照时长，帮助鸟提前准备迁徙；风况影响具体哪天出发，目的地食物影响繁殖。“different time scales”是不同时间尺度，季节准备不等于立即出发。\n解析：全文关注不同信号和时间尺度怎样影响迁徙。不是日长决定每只鸟的精确出发日；目的地条件也没取代体内节律；仅用短期天气更解释不了整套过程。\n下次：主旨题先按阶段梳理“准备—出发—到达后的结果”，再匹配各阶段的影响因素。选覆盖多个层次的答案，不要把一个因素夸成决定全部的唯一原因。"),
        item('Why is day length a useful seasonal cue?', 'It is more predictable than short-term weather.', 'It reflects current wind conditions along the migration route.', 'It changes as soon as destination food becomes plentiful.', 'It responds more quickly to unusual local temperatures.', "读懂：Changes in day length 是白昼长短的变化，它比某一天突然暖或冷更能稳定地提示季节，所以是较可预测的迁徙准备信号。\n解析：日长有用在于比短期天气更可预测，不是能反映沿途此刻的风；它也不随目的地食物突然丰富而立刻改变，更不是对异常气温反应更快。\n下次：遇到“为什么某信号有用”，找到原文比较的是稳定性、速度还是准确性，再沿同一标准排除。这里强调可预测，不能把它误换成实时追随风、气温或食物变化。"),
        item('Why might a prepared bird delay departure?', 'Unfavorable winds could make the journey costly.', 'Shorter days have prevented its seasonal preparation.', 'Stored energy automatically disappears when departure is delayed.', "Its arrival schedule has already adjusted to the destination's food peak.", "读懂：鸟即使已经准备好迁徙，也可能因强风推迟出发。costly 在飞行语境里是“耗能很大”，不是指需要多付钱。\n解析：不利风况会增加飞行代价，所以鸟可能等待。准备已经完成，不能说日短阻止了准备；文中没有能量一延迟就自动消失的机制；已适应目的地食物高峰也不是这里的推迟原因。\n下次：题目强调“已准备好却没有出发”时，区分长期准备与眼前触发行动的条件。回到当地风况找解释，不要用尚未完成准备的答案否定题干前提。"),
        item('What mismatch does climate change create?', 'Food peaks can shift relative to established arrival schedules.', 'Departure weather may change while seasonal day length changes equally fast.', 'Birds may store more energy even when their food needs remain constant.', 'All populations may arrive earlier by the same amount each year.', '读懂：food availability 是食物的供应情况；目的地食物最丰富的时段可能提前得更快，而远方鸟依赖的日长信号没有同样跟上。仍按老时间表抵达，就可能错过食物高峰。\n解析：错配发生在食物高峰与既定到达时间之间，不是天气与日长同速变化；储能增加不是文中这条关系；各群体调整能力不同，不能说全部每年都提前一样多。\n下次：问 mismatch 时，明确写出“两件应当对齐的事”，再检查哪个变化更快。不要只挑带有气候、能量等相关词的选项，要保留原文真正的时间错位关系。'),
        item('Why measure breeding outcomes as well as arrival dates?', 'To assess whether changed timing actually benefits the birds.', 'To decide whether day length has become less predictable.', 'To separate the effect of wing size from stored energy.', 'To assume that a calendar shift alone is a successful adaptation.', "读懂：“breeding outcomes”是繁殖结果，“a successful adjustment”是成功适应。研究者要把到达时间、食物高峰与繁殖结果一起比较，才能知道提前到达有没有实际帮助。\n解析：测繁殖结果是为了评估改变时间是否带来实际好处。不是检验日长是否变得不可预测；也没研究翅膀大小与储能的分别影响；仅凭日期变化就认定适应成功，正是原文要避免的做法。\n下次：研究目的题区分“观察到行为变化”和“证明变化有效”。问为何增加一个结果指标，就想它能检验什么实际成效，而不是把表面变化自动当作成功。"),
    ]),
    ("Printing and the survival of texts", "Printing allowed more copies of a text to circulate, but abundance did not guarantee survival. Printed materials used for everyday purposes, such as notices and inexpensive song sheets, were often discarded once they had served their immediate function. A costly volume stored in a library might survive for centuries, while thousands of cheap copies of another work disappeared.\n\nInitial sales describe circulation, whereas a surviving copy also reflects what escaped later damage or disposal. [A] This uneven survival influences historical research. The documents available today are not a random sample of what people read. They reflect decisions about collection and preservation as well as accidents involving fire, water, or reuse. [B] Such fragments can reveal texts absent from formal library catalogs.\n\n[C] Evidence from surviving objects must therefore be combined with other records. Publishers' accounts may indicate that a missing work was produced in large numbers, and personal letters can show that people discussed it. These sources do not reconstruct every lost page, but they challenge the assumption that the most frequently preserved works were necessarily the most widely read. [D] The archive records a history of preservation in addition to a history of production.", [
        item('What is the main argument?', 'Surviving texts do not directly represent everything people once read.', 'The number of surviving copies closely reflects original popularity.', 'Cheap print rarely circulated beyond the libraries that preserved it.', 'Production records provide more complete texts than surviving copies.', "读懂：“abundance did not guarantee survival”意为印得多不保证留存得多。日常印刷品可能用完就丢，贵重馆藏却能留存几百年；现存资料不是过去读物的随机样本。\n解析：存世文本不能直接代表当年人们读过的一切。存量不一定反映原先流行度；廉价读物并非很少流出图书馆；出版记录能补充印量信息，却不能比原件提供更完整的正文。\n下次：历史材料主旨题分开“当年生产或使用多少”和“后来留下多少”。追踪保存、损坏、丢弃的筛选过程，警惕把现有样本当成过去全貌。"),
        item('Why were everyday printed materials often lost?', 'They were discarded after their immediate use.', 'Their low prices prevented libraries from acquiring any copies.', 'Binders preserved complete copies instead of reusing loose sheets.', 'Their intended purpose gave readers little reason to discard them.', "读懂：notices and inexpensive song sheets 是通知、廉价歌页等日常印刷品；它们完成眼前用途后常被 discarded，也就是扔掉。\n解析：失传原因是用完即弃。没有说价格低导致图书馆一份也不能收；装订者保存完整本而不再用散页，也不是这里的丢失原因；说原定用途让人不愿丢弃，恰好反转了原文的关系。\n下次：问某类物品为什么容易失传，先看它的使用期限和使用后处理方式。区分“曾印得多不多”与“用完有没有保存”，不要仅凭价格推断收藏能力。"),
        ('Where would the following sentence best fit in the passage?\n\nHistorians sometimes find ordinary printed sheets inside old book bindings because binders used unwanted paper as a strengthening material.', ['Position [A]', 'Position [B]', 'Position [C]', 'Position [D]'], 1, "读懂：待插句说装订者用废纸加固旧书，因此历史学家有时能在装订内部找到普通印刷纸张。它提供了再利用后留下的具体碎片。\n解析：选 Position B：前句提到 reuse，即再利用，插句举例；后句 Such fragments 正好回指这些纸片。Position A 过早，割开存留不均的说明；Position C、Position D 都在 Such fragments 后，所指对象出现太晚。\n下次：含 Such 的句子需要前文先出现具体事物。把“再利用→找到纸片→这些碎片的价值”连起来，再确认上下句都紧接同一对象。"),
        item("Why does the author mention publishers' accounts?", 'They can provide evidence of works whose copies have vanished.', 'They identify all the readers of surviving library copies.', 'They establish that frequently preserved works had the largest print runs.', 'They can reconstruct the exact wording of every missing page.', "读懂：publishers' accounts 是出版商的账目记录。即使某作品的纸本已不见，这类记录仍可能显示它当年印了很多份。\n解析：提到账目是为了补充已失传作品的证据。账目并不能认出所有读者；它也不证明保存最多的书原来印量最大，作者正质疑这种等同；更无法还原每张缺页的原句。\n下次：问一种史料的作用，先区分它能证明“作品存在、数量多少”还是“具体内容、谁阅读”。只选记录确实支持的层次，不要把辅助证据夸成能完整恢复过去。"),
        item("The word 'abundance' most nearly means", 'a large quantity.', 'careful preservation.', 'wide historical influence.', 'high monetary value.', "读懂：开头说印刷让更多副本流通，紧接着说 abundance 不保证存留下来。因此这个词承接的是 copies 的数量多，而不是保存得好。\n解析：abundance 指“大量”。精心保存是另一回事；历史影响广与数量多并不等同；价值高也不合此处，因为后面恰用大量廉价印刷品消失作对比。\n下次：抽象名词词义题先向前找它概括的具体内容，再用后面的例子检查。这里“更多副本→大量→仍会丢失”连得上，若代入“精心保存”就改变了作者的对比。"),
    ]),
    ("The role of sleep in learning", 'Practice is central to learning a new skill, but improvement does not always occur during practice itself. Performance can become more stable after an interval that includes sleep. Researchers describe this stabilization as one aspect of memory consolidation, a set of processes through which recently acquired information becomes less vulnerable to interference.\n\n[A] Experiments often compare people who learn the same task and are tested after different intervals. [B] Designing a fair comparison is difficult because sleep is connected with time of day, fatigue, and previous experience. If one group trains in the morning and another late at night, a later difference may have more than one explanation. [C]\n\nThe results also depend on the task. Remembering word pairs and learning a sequence of finger movements involve partly different systems, so a benefit observed for one activity should not automatically be generalized to all learning. Nor does consolidation make practice unnecessary. It operates on material that a person has encountered. [D] For students, the practical implication is to consider the schedule surrounding practice, while recognizing that sleep cannot supply knowledge that was never learned in the first place.', [
        item('What does memory consolidation do in the passage?', 'It can stabilize newly learned information.', 'It makes every new memory equally resistant to interference.', 'It produces new information during sleep without previous exposure.', 'It improves performance only while a task is being practiced.', "读懂：memory consolidation 是记忆巩固，让刚学到的信息更稳定、更不容易被其他信息干扰。文章说，进步有时会在包含睡眠的一段间隔后出现。\n解析：作用是稳定新学信息，不是让每段新记忆都同样抗干扰；也不能在从未接触知识的情况下凭睡眠生成知识；说改善只发生在练习当时，与开头的对比相反。\n下次：概念作用题先分清“处理已经学到的内容”和“产生从未学过的内容”。再检查程度词，原文的“更稳定”不能扩大成所有记忆效果完全一致。"),
        item('Why can morning and evening training groups be difficult to compare?', 'Time of day and fatigue may also affect performance.', 'The later test necessarily uses a different type of task.', 'Training time changes while fatigue remains identical in both groups.', 'The groups must have acquired exactly the same earlier experience.', "读懂：“time of day, fatigue, and previous experience”分别是时段、疲劳和以往经验。早晨组与深夜组不只差在是否睡过，因此后测差异不能全算在睡眠头上。\n解析：难比较是因为时段和疲劳等因素可能干扰判断。没有说后测必然换任务；也不能认定两组疲劳完全相同；“先前经验必须一模一样”不是文中给出的事实或困难原因。\n下次：比较实验结果时，先问除了研究因素，两组还可能在哪些方面不同。只要这些差别也能影响结果，就不能把全部差异直接归因于睡眠这一项。"),
        ('Where would the following sentence best fit in the passage?\n\nCareful studies use additional comparison groups to separate these influences.', ['Position [A]', 'Position [B]', 'Position [C]', 'Position [D]'], 2, "读懂：待插句说严谨研究会加设比较组，把 these influences，即这些影响因素，分开考察。它是在回应前文的实验比较难题。\n解析：选 Position C：前面已经点出时段、疲劳和经验，并用早晚训练说明多种解释；插句补上控制办法，后段再转向任务差异。Position A、Position B 尚未列出这些因素；Position D 已在谈练习与知识，回头讲实验分组会打断论述。\n下次：看到 these 等回指词，先定位完整的因素清单，再检查插句是否承担“问题→解决办法”的收尾作用，并留意下一段是否换了话题。"),
        item('What advice does the author give students in the final paragraph?', 'Plan the time around practice as well as the practice itself.', 'Use results from a familiar task to schedule every kind of learning identically.', 'Judge consolidation only by the ease of performance during practice.', 'Change training time without considering fatigue in later comparisons.', "读懂：“the schedule surrounding practice”是练习前后的时间安排；“knowledge that was never learned”是从未学过的知识。睡眠可帮助巩固已学内容，却不能替代学习本身，不同任务收益也未必相同。\n解析：合理做法是既安排练习，也考虑练习前后的时段。不能把一种任务的结果套给所有学习；只看练习当时是否轻松会漏掉延后变化；改变训练时间后也不能忽视疲劳。\n下次：从研究提炼做法时，先找作者明确给的建议，再保留适用边界。这里要同时保留“仍需练习、安排时间、注意任务差别”，不能化成一种万能作息。"),
        item("The word 'vulnerable' most nearly means", 'susceptible to being affected.', 'capable of being deliberately strengthened.', 'likely to remain permanently unchanged.', 'difficult to distinguish from older knowledge.', "读懂：信息变得 less vulnerable to interference，意思是“更不容易受干扰影响”。vulnerable 本身说的是容易受影响，less 才把这种程度降低。\n解析：词义是“容易受到影响的”，不是可被主动加强，也不是永久不变，或难与旧知识区分。记忆巩固可能使信息更稳定，但不能把整句的效果当成 vulnerable 单独的意思。\n下次：遇到 less、not 等修饰词，先暂时拿掉它们判断目标词，再放回检查整句方向。否则容易把“较不容易受影响”误解为目标词本身就是“不变”。"),
    ]),
    ("Natural ventilation in buildings", "Before mechanical cooling became common, many buildings relied on openings and internal spaces to encourage air movement. A window on one side and an outlet on another can allow wind to carry air through rooms. Warm air can also rise through a tall central space and escape near the roof, drawing cooler air into lower levels. These mechanisms depend on differences in pressure and temperature.\n\nDesigners interested in reducing energy use have revisited these approaches. However, natural ventilation is not equally effective everywhere. Outdoor noise may discourage occupants from opening windows, and polluted air can make increased airflow undesirable. In humid climates, moving air may improve comfort without removing enough moisture to protect sensitive materials.\n\nConsequently, some buildings combine natural and mechanical systems. Controls may permit open windows during suitable weather and activate equipment when outdoor conditions become unfavorable. Success depends partly on how occupants understand the system. If instructions are unclear, a person may run cooling equipment while leaving windows open, increasing energy use. Evaluations therefore examine actual operation as well as design calculations. A building's predicted efficiency is only one part of the evidence needed to judge its performance in everyday use.", [
        item('What is the passage mainly about?', 'How natural ventilation works and what limits its usefulness.', 'Why pressure differences are more important than actual building use.', 'How natural ventilation can replace mechanical systems in every climate.', 'Why energy calculations make observations of occupants unnecessary.', "读懂：“combine natural and mechanical systems”是结合自然与机械通风。全文先介绍空气流动，再讲噪声、污染、湿度等限制，最后谈混合系统及实际操作，重点是方法及适用条件。\n解析：主旨是自然通风的机制与适用局限。不是强调压力比实际使用更重要；也不是所有气候都能不用机械设备；设计计算更不能替代对住户操作的观察。\n下次：技术说明文主旨题按“怎样工作—何时受限—如何应用”串起各段。若选项只抓一个物理原理，或把有条件可行说成到处适用，就不能概括全篇。"),
        item('What can rising warm air do?', 'Draw cooler air into lower parts of a building.', 'Keep cooler air from entering at lower openings.', 'Remove humidity without depending on outdoor conditions.', 'Create airflow only when both openings are at the same height.', "读懂：“escape near the roof”是从屋顶附近排出，“drawing cooler air into lower levels”是带动凉空气进入较低楼层。上升暖空气排出与下部凉空气进入构成连贯过程。\n解析：上升暖空气能促使凉空气从低处进入，不是阻止它进入。文中没说这能不受室外条件影响地除湿；入口和出口也不必同高，这个例子恰是一高一低。\n下次：机制题按箭头画出“哪里进入→如何运动→哪里排出”，再核对选项的方向和条件。通风使空气流动，不自动等于已经除湿，别把相关效果混在一起。"),
        item('Why might outdoor conditions make open windows unsuitable?', 'Noise or pollution can reduce their practical value.', 'Lower energy use necessarily makes the room less comfortable.', 'Natural pressure differences prevent sound from entering.', 'Humid air removes moisture from sensitive materials more effectively.', "读懂：“Outdoor noise”是室外噪声，“polluted air”是受污染空气，它们会让开窗不实用；“without removing enough moisture”是未除掉足够水分，说明凉快不一定等于除湿达标。\n解析：噪声或污染会降低开窗的实用价值。节能不必然让人不舒服；压力差并没有被说成能隔音；湿空气也不是更能带走敏感材料的水分，这与除湿不足的提醒相反。\n下次：问何时一种设计不适合，先列文中的环境限制，再区分舒适、空气质量、除湿这些不同目标。某一方面改善，不能推出其他方面也必然改善。"),
        item('What is the purpose of combining ventilation systems?', 'To use different methods as outdoor conditions change.', 'To use mechanical cooling while keeping windows open in all weather.', 'To eliminate the effect of occupants on energy consumption.', 'To base operation on predicted efficiency without checking conditions.', "读懂：“during suitable weather”是天气合适时，“when outdoor conditions become unfavorable”是室外条件变差时。前者可开窗，后者启用设备，让自然与机械方式各用在合适条件下。\n解析：因此是随室外情况选用不同办法，不是任何天气都边开窗边制冷。住户操作仍会影响耗能；系统也不能只依设计预测而不查看现实条件。后文把误开窗又开制冷当作增加耗能的例子。\n下次：判断组合方案的目的，找到切换条件，再给每种模式配上适用情境。“结合两种方法”不等于“两种永远同时开”，也不等于不需要使用者正确操作。"),
        item('What does the final paragraph imply?', "Users' actions can affect whether a design achieves its expected efficiency.", 'A design meeting its calculations needs no clear operating instructions.', 'Actual operation matters only when mechanical cooling is absent.', 'Open windows always improve the efficiency of a cooling system.', "读懂：“actual operation”是实际运行，“design calculations”是设计计算。说明不清时，人可能边开窗边用制冷设备，反而费电，所以判断效果不能只看纸面预测。\n解析：可推断人的操作会影响设计能否达到预期效率。计算达标不代表无需清晰说明；有机械制冷时实际操作照样重要；开窗也不是永远提高制冷效率，文中的例子正好否定了这一点。\n下次：从设计推到效果时，补问“用户实际怎样使用”。把预测指标与真实表现分开，并找可能让两者偏离的具体行为，避免把纸面节能直接当成日常节能。"),
    ]),
]
