"""Complete practice blocks mapped to ETS task specifications or sample parts."""

TASK_STRUCTURE = {
    'complete_words': dict(label='填词题', count_options=[1, 2], unit='篇', units_per_set=1, group_sizes=[10],
        description='在完整短文中补全 10 个单词缺失的后半部分，结合语境、词形和语法作答。',
        exam_part='对应 ETS 官方样题的一篇 Complete the Words：10 空。', source_ids=['ets_practice']),
    'read_daily_life': dict(label='日常生活', count_options=[2, 4], unit='篇', units_per_set=2, group_sizes=[2, 3],
        description='随机抽取邮件、通知、消息等完整材料。短材料配 2 题，长材料配 3 题；题数随抽到的材料确定。',
        exam_part='对应 Read in Daily Life：官方每篇配 2 或 3 题，取决于材料长度。本练习随机选篇，不固定短长配比。', source_ids=['ets_overview', 'ets_practice']),
    'read_academic_passage': dict(label='学术文章', count_options=[1, 2], unit='篇', units_per_set=1, group_sizes=[5],
        description='阅读约 200 词的学术短文，回答主旨、细节、词义、推断和篇章作用等 5 个小题。',
        exam_part='对应 ETS 官方样题的一篇 Read an Academic Passage：5 题。', source_ids=['ets_practice']),
    'listen_choose_response': dict(label='听答题', count_options=[8, 16], unit='题', units_per_set=8, group_sizes=[1],
        description='听一句提问或陈述，选择符合语境的回应。一份包含 8 题。',
        exam_part='按 ETS 官方样题 Test 1 听力 Module 1 的短回应部分组卷：8 题。', source_ids=['ets_practice']),
    'listen_conversation': dict(label='短对话', count_options=[2, 4], unit='组', units_per_set=2, group_sizes=[2],
        description='听两段校园或日常对话，每段回答 2 题，一份共 4 个小题。',
        exam_part='按 ETS 官方样题 Test 1 听力 Module 1 的对话部分组卷：2 段，各 2 题。', source_ids=['ets_practice']),
    'listen_announcement': dict(label='校园公告', count_options=[1, 2], unit='组', units_per_set=1, group_sizes=[2],
        description='听一段活动安排或校园通知，回答 2 题，抓住目的、变化、条件和行动要求。',
        exam_part='对应 ETS 官方样题的一段 Listen to an Announcement：2 题。', source_ids=['ets_practice']),
    'listen_academic_talk': dict(label='学术讲座', count_options=[1, 2], unit='组', units_per_set=1, group_sizes=[4],
        description='听一段学术讲解，回答主要观点、例子、推断和结构等 4 个小题。',
        exam_part='对应 ETS 官方样题的一段 Listen to an Academic Talk：4 题。', source_ids=['ets_practice']),
    'build_sentence': dict(label='造句题', count_options=[10, 20], unit='题', units_per_set=10, group_sizes=[1],
        description='根据对话语境排列词语，构成完整、合乎语法的句子或问句。一份包含 10 题。',
        exam_part='对应正式写作中的 Build a Sentence 部分：10 题。', source_ids=['ets_specs', 'ets_practice']),
    'write_email': dict(label='写邮件', count_options=[1, 2, 3], unit='题', units_per_set=1, group_sizes=[1],
        description='根据给定情境写一封邮件，完成指定沟通目的。一份 1 题，官方作答时间 7 分钟。',
        exam_part='对应正式写作中的 Write an Email：1 封邮件。', source_ids=['ets_specs', 'ets_practice']),
    'academic_discussion': dict(label='学术讨论', count_options=[1, 2, 3], unit='题', units_per_set=1, group_sizes=[1],
        description='回应教授的问题与同学观点，明确立场并用理由和例子支持。一份 1 题，官方作答时间 10 分钟。',
        exam_part='对应正式写作中的 Write for an Academic Discussion：1 篇回应。', source_ids=['ets_specs', 'ets_practice']),
    'listen_repeat': dict(label='复述题', count_options=[1, 2, 3], unit='组', units_per_set=1, group_sizes=[7],
        description='一份包含同一场景下的 7 句，由短到长。听后复述，尽量保留原句词语与顺序。',
        exam_part='对应正式口语中的 Listen and Repeat：7 句，保留完整场景与句序。', source_ids=['ets_specs']),
    'take_interview': dict(label='模拟面试', count_options=[1, 2, 3], unit='组', units_per_set=1, group_sizes=[4],
        description='一份包含围绕同一主题的 4 个访谈问题；无单独准备阶段，每问作答最多 45 秒。',
        exam_part='对应正式口语中的 Take an Interview：同一访谈的 4 问。', source_ids=['ets_specs', 'ets_overview']),
}

DIFFICULTY_POLICY = '每份至少含适中或困难题，可混合、全适中或全困难；不抽取整份全简单的组合。材料不拆分，保留题目原有难度。'
