"""Reviewed contexts, blank frames and alternative sentence-building answers."""

# Braced groups become movable tiles; everything else stays fixed in the
# public sentence frame. The optional second value is an unused distractor.
# These are original items, not transcriptions of the ETS sample questions.
FRAMES = {
    'W01': ('{the research team} {published} {its results} {online}.', None),
    'W02': ('{students} {can} {reserve} {a study room} {through the library}.', 'does'),
    'W03': ('{because} {the trail} {was} {wet} {the class} {walked} {slowly}.', None),
    'W04': ('Our professor {asked} {whether} {the evidence} {supported} {the claim}.', 'did'),
    'W05': ('{the new schedule} {allows} commuters {to avoid} {rush hour}.', None),
    'W06': ('{after the experiment} {we} {recorded} {each measurement} {carefully}.', 'was'),
    'W07': ('{the museum} {will display} {photographs} {from} the early expedition.', None),
    'W08': ('{if} {the weather} {improves} {the market} {will} {open} {outside}.', 'would'),
    'W09': ('{many languages} {borrow} {words} {when} {cultures} {come into contact}.', None),
    'W10': ('The advisor {recommended} {that} {I} {compare} {several sources}.', 'to'),
    'W31': ('{could} {you} {tell me} {where} the registration office {is}?', 'does'),
    'W32': ('Where {are} {the books} {that} {arrived} {yesterday}?', None),
    'W33': ('{although} {the experiment} {failed} {the results} {raised} {an interesting question}.', 'but'),
    'W34': ('{How long} {have} {you} {been collecting} {temperature records}?', 'did'),
    'W35': ('{Does} {the application} {have to} {be submitted} {before} {the office closes}?', 'has'),
    'W36': ('{would you mind} {explaining} {the final step} {again}?', None),
    'W37': ('{Were} {the tutor} {and the students} {both available} {on Monday}?', None),
    'W38': ('The {more carefully} {we plan}, the {less time} {we waste}.', None),
    'W39': ('{I} {would have} {joined} {the trip} {if} {I} {had seen} {the announcement}.', 'would'),
    'W40': ('Does {the article} {explain} {why} {some coastal communities} {moved} {inland}?', 'did'),
    'W41': ('{Did} {all of the participants} {agree} {with} {the proposed changes}?', 'agreed'),
    'W42': ('Have {you} {compared} {your findings} {with} {those of earlier studies}?', None),
    'W43': ('{Had} {the last train} {already left} {when} {you reached} {the station}?', 'did'),
    'W44': ('{Is} {this} {the first course} {you have taken} {outside} {your department}?', None),
    'W45': ('{What} {surprised} {the researchers} {about} {the recovery}?', 'did'),
    'W46': ('Do {you know} {whether} {we need} {to arrange access} {to the building}?', 'do'),
    'W47': ('{the equipment} {is} {too heavy} {for one person} {to} {carry} {safely}.', None),
    'W48': ('Can {you explain} {what} {led the team} {to revise} {its conclusion}?', 'did'),
    'W49': ('{Has} {the museum} {where she volunteers} {opened} {its new gallery} {yet}?', None),
    'W50': ('{if} {the room} {had better lighting} {we} {could display} {the photographs} {there}.', 'will'),
    'W51': ('How {do} {people} {adapt} {when} {they move} {to an unfamiliar environment}?', 'does'),
    'W52': ('Do {you remember} {how many copies} {of our proposals} {we} {should bring}?', 'do'),
    'W53': ('Could {you explain} {why} {the committee} {waited} {before making} {a decision}?', 'did'),
    'W54': ('{Does} {the software} {make} {it easier} {to organize} {large collections of notes}?', 'makes'),
    'W55': ('{despite the additional cost} {the department} {chose} {the more durable materials}.', 'although'),
    'W56': ('How long {have} {you} {been waiting} {for a response} {from the office}?', None),
    'W57': ('{What} {did the survey} {reveal} {about} {what commuters} {needed most}?', None),
    'W58': ('There is {no reason} {to assume} {that} {every result} {will be} identical.', None),
    'W59': ('{Is} {the footpath} {shorter} {than} {the road} {through town}?', 'does'),
    'W60': ('{Can} {we} {begin the analysis} {before} {all the samples} {have arrived}?', None),
    'W61': ('She {suggested} {that} {we} {discuss} {the budget} {before choosing a venue}.', 'to'),
    'W62': ('The question is {not} {whether} {to cooperate} {but} {how} {to share the work}.', None),
    'W63': ('{anyone} {who wishes} {to attend} {should register} {by Thursday}.', 'to'),
    'W64': ('{the report} {would be} {clearer} {if} {it} {included a diagram}.', None),
    'W65': ('Have {you checked} {whether} {every device} {has been} {switched off}?', 'have'),
    'W66': ('It was {the unexpected delay} {that} {forced us} {to change} {our route}.', None),
    'W67': ('{the lecturer} {emphasized} {the importance of} {checking} {sources} {independently}.', 'to'),
    'W68': ('{Which of the ideas} {discussed} {at the meeting} {came} {from first-year students}?', 'did'),
    'W69': ('{could} {the materials} {be delivered} {before} {the workshop} begins?', 'are'),
    'W70': ('{rather than repeat the whole experiment} {we} {tested} {the uncertain measurement} {again}.', None),
}

CONTEXTS = {
    'W01': 'What did the research team do with its results?',
    'W02': 'How can students reserve a study room?',
    'W03': 'Why did the class walk slowly?',
    'W04': 'What did the professor ask about the evidence and the claim?',
    'W05': 'How does the new schedule help commuters?',
    'W06': 'What did you do after the experiment?',
    'W07': 'Which photographs will the museum display?',
    'W08': 'Under what condition will the market open outside?',
    'W09': 'What happens to languages when cultures come into contact?',
    'W10': 'What did the advisor recommend that you compare?',
    'W31': 'I need to register for my classes, but I am new to this campus.',
    'W32': 'The library received the books we requested yesterday.',
    'W33': 'Did the failed experiment still produce something useful?',
    'W34': 'Our project uses temperature records from several seasons.',
    'W35': 'The application portal closes at the end of the day.',
    'W36': 'I can explain any part of the procedure you are unsure about.',
    'W37': 'I tried to arrange a meeting for the tutor and the students last week.',
    'W38': 'How does more careful planning affect wasted time?',
    'W39': 'Explain why missing the announcement prevented you from joining the trip.',
    'W40': 'This article discusses the history of several coastal communities.',
    'W41': 'The committee proposed some changes at yesterday’s meeting.',
    'W42': 'I have finished collecting the data for my research project.',
    'W43': 'We reached the station much later than we had planned.',
    'W44': 'I am taking an introductory course in another department.',
    'W45': 'The research team reported an unexpected result.',
    'W46': 'Several visitors have asked about getting into the building after hours.',
    'W47': 'Why is it unsafe for one person to carry the equipment?',
    'W48': 'The team revised its conclusion after checking the figures.',
    'W49': 'My friend volunteers at a museum with a new gallery.',
    'W50': 'Explain how better lighting would make the room suitable for photographs.',
    'W51': 'Our project investigates how people adapt to unfamiliar environments.',
    'W52': 'The coordinator asked everyone to bring copies of their proposals.',
    'W53': 'The committee made its decision after reviewing all the evidence.',
    'W54': 'I am using a new program to organize my research notes.',
    'W55': 'Which materials did the department choose despite their cost?',
    'W56': 'The office has not sent me a response yet.',
    'W57': 'The survey was designed to identify commuters’ priorities.',
    'W58': 'Is there a reason to assume that every result will be identical?',
    'W59': 'I have heard that a footpath leads to the station.',
    'W60': 'Some samples have arrived, but the final delivery is still missing.',
    'W61': 'What did she suggest discussing before choosing a venue?',
    'W62': 'Explain that cooperation is agreed, but dividing the work is unresolved.',
    'W63': 'What should a person wishing to attend do by Thursday?',
    'W64': 'How would including a diagram improve the report?',
    'W65': 'We are the last people leaving the laboratory tonight.',
    'W66': 'Emphasize the unexpected delay as the reason you changed your route. Begin with It.',
    'W67': 'What did the lecturer emphasize about checking sources?',
    'W68': 'Several first-year students contributed useful ideas at the meeting.',
    'W69': 'Our workshop begins early on Friday morning.',
    'W70': 'Explain what you tested instead of repeating the whole experiment.',
}

ALTERNATIVES = {
    'W01': ['Online, the research team published its results.'],
    'W02': ['Through the library, students can reserve a study room.'],
    'W03': ['The class walked slowly because the trail was wet.', 'Because the trail was wet, the class slowly walked.', 'The class slowly walked because the trail was wet.'],
    'W06': ['We recorded each measurement carefully after the experiment.', 'We carefully recorded each measurement after the experiment.', 'After the experiment, we carefully recorded each measurement.', 'Carefully, we recorded each measurement after the experiment.'],
    'W08': ['The market will open outside if the weather improves.'],
    'W09': ['When cultures come into contact, many languages borrow words.'],
    'W33': ['The results raised an interesting question although the experiment failed.'],
    'W34': [],
    'W35': [],
    'W36': ['Would you mind again explaining the final step?'],
    'W37': [],
    'W39': ['If I had seen the announcement, I would have joined the trip.'],
    'W43': [],
    'W47': ['The equipment is too heavy for one person to safely carry.'],
    'W48': [],
    'W49': [],
    'W50': ['We could display the photographs there if the room had better lighting.'],
    'W55': ['The department chose the more durable materials despite the additional cost.'],
    'W57': [],
    'W60': [],
    'W63': ['By Thursday, anyone who wishes to attend should register.'],
    'W64': ['If it included a diagram, the report would be clearer.'],
    'W65': [],
    'W67': ['The lecturer emphasized the importance of independently checking sources.'],
    'W70': ['We tested the uncertain measurement again rather than repeat the whole experiment.', 'Rather than repeat the whole experiment, we again tested the uncertain measurement.'],
}
